### ISSUE TITLE
Make two_regions_example_opt.py executable

### ISSUE THREAD

**Issue by gplssm** [oemof/oemof#100]
The example two_regions_example_opt.py is only executable if oemof.db is checked out to dev branch. Would be helpful to have this executable even with checked out master branch of oemof.db. Refers to https://github.com/oemof/oemof.db/issues/6

**Comment by birgits** [comment]
@gnn: Anything new here?

**Comment by uvchik** [comment]
@birgits : You used and improved it within your application (smenos). Do you think it is worth to keep it?

**Comment by birgits** [comment]
It was definitely very useful for us as a first example on how to set up a multi-region energy system and on how to automatically add renewable and conventional power plants using the energy map and Kraftwerksdatenbank. I think it is worth keeping and I would also offer to help fixing it; not for this release but the next one though, since there are only two days left until the April release.

**Comment by uvchik** [comment]
It has to be moved to oemof.db anyway, because it depends on the database. You could do that before the release and fix the example later.

**Comment by gnn** [comment]
I'm with @uvchik on moving this to `oemof.db` that way the example is still there, we don't have a broken example in the release any more, we can fix the example before doing a first release of `oemof.db` and on top of that the example is contained within the branch with which it has to be run, which fixes the original issue, albeit probably not in the way @gplssm anticipated (sorry for that).
I'll offer to do the move before the release, @birgits. Just say so.

**Comment by birgits** [comment]
I already moved it to oemof.db and opened a new issue there (https://github.com/oemof/oemof.db/issues/13).
