### ISSUE TITLE
February release is coming soon!

### ISSUE THREAD

**Issue by cswh** [oemof/oemof#108]
@oemof/oemof-main 

The February release will be released on Wednesday 2016-03-02!

**Comment by cswh** [comment]
it is on the way!

**Comment by cswh** [comment]
And finished. Thanks a lot to @uvchik because the [How-to-release-wiki](../wiki/How-to-release)i is very helpful. I updated and added some things to hopefully aid the next releasers.

* See the documentation at http://oemof.readthedocs.org/en/stable/
* See the post at https://oemof.wordpress.com/
* Get the new version at https://pypi.python.org/pypi/oemof

**Comment by uvchik** [comment]
Thank you for updating the wiki. 

The funny thing is that we do have a documentation at pythonhosted again. I'm okay with that even though it took me a little while to create the overview page at pythonhosted (see the discussion on [issue 1 downwards from January the 26th](1#issuecomment-174558386 )).

We should decide that 'finally', so that we do not change it all the time.

**Comment by ckaldemeyer** [comment]
> Thank you for updating the wiki.

> The funny thing is that we do have a documentation at pythonhosted again. I'm okay with that even though it took me a little while to create the overview page at pythonhosted (see the discussion on issue 1 downwards from January the 26th).

> We should decide that 'finally', so that we do not change it all the time.

I am for removing it and putting back Uwes link to RTD  as I mentioned in the last discussion.

**Comment by cswh** [comment]
That is ok for me. I was just following the wiki, where it was still on the list of todos. I updated the wiki now with a hint. If we just go to the static file, we should remove it from the wiki.
