### ISSUE TITLE
Emission optimization

### ISSUE THREAD

**Issue by SanderNielen** [oemof/oemof#112]
Currently, it is possible to assign CO2 emission data to components. However, I did not find functions that calculate the total emissions of the system, or use CO2 emissions as the optimization objective. 
If these functionalities do not exist yet, I will put some effort in it.

**Comment by simonhilpert** [comment]
Hi Sander(?), 

you are right these functionalities do not exist atm. Actually we are in a redesign process until may. The version 0.1.0 that will be released in end May/June will probably not be back-compatible  with the current oemof structure. 
Nevertheless you can easily extend the framework with the co2 functionality. I think we will be able to transfer this code.

1. You should start a feature branch e.g. features/add-co2-emissions  and a pull request, so that other developers are informed and the process is transparent.  
2. I would suggest you simply add expressions to solph.objective_expressions that sum co2 -emissions you need (e.g. variable, fix, invest, etc). 
3. In a next step you can add a objective in solph.predefined_objectives which makes use of these
expressions. 
4. Please code according to pep8 and add docstrings etc, Please check out the [developer notes] http://oemof.readthedocs.org/en/stable/developer_notes.html

I think in this way it's pretty straight forward and you can work your way through code/structure with the already implemented cost objective/obj. expression

**Comment by SanderNielen** [comment]
Hi Simon,

Thanks for the suggestions. I'll do my best to stick to the pep8 and developer guidelines. For the rest, I'm quite confident everything will work out.

**Comment by simnh** [comment]
Can this be closed, what is the progress? @SanderNielen

**Comment by SanderNielen** [comment]
I'm still working on it. You can close this issue if you want. I will submit a pull request if I have finished the objective function.

**Comment by simnh** [comment]
Ok. Please close, once emmission optimization is finished and merged.
