### ISSUE TITLE
Multiple energysystems at once / automatic entity adding to energysystem object

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#140]
This is not really possible / intuitive as entities are added autmatically. So if the add method is used 
the entity is added to all exisiting energysystems.

**Comment by simnh** [comment]
related to issue #139

**Comment by uvchik** [comment]
At the moment I do not see the need of two energy systems at once but of course this could be a good feature for some projects. An oemof energy system can already contain different energy systems whether or not they are connected.

![issue_140_a](https://cloud.githubusercontent.com/assets/4760584/14524421/84d60636-0238-11e6-88c6-f378e001a814.png)

**Comment by simnh** [comment]
yes for some projects that already exist, this is why I created an issue. 

I think it should be possible to have multiple energy systems at once without messing around when entities are created etc.. at the moment due to automatic insertion of entities this is - as I said - not really an intuitive behaviour of the es-class.

**Comment by uvchik** [comment]
But than it is more a decision than an enhancement.

We could remove the auto insertion and use an "add" method instead. I do agree. This would lead to a little more but cleaner code.

**Comment by uvchik** [comment]
@oemof/oemof-core: What do you think?

**Comment by simnh** [comment]
@gnn : can you make an proposal what a clear structure to do that would look like? 

For me it would be ok to have a flag: "auto_insert" for entities which would be set to true by default. 
But I know @gnn doesnt like attributes... :)

**Comment by gnn** [comment]
I already commented on #139 with what I thought was appropriate there. Concerning the questions raised here (hope I don't forget any):

Any newly created entities are indeed added automatically to the *most recently created* energy system. This is not explicitly stated but can be inferred from the [`Entity.registry`'s documentation](../blob/6dadf8eae1e61b1bd901569d619d364a668f6000/oemof/core/network/__init__.py#L35), specifically:

> [..] When you instantiate an :class:`EnergySystem <oemof.core.energy_system.EnergySystem>` it automatically becomes the entity registry, [..]

which implies that the current entity registry is overwritten. This was more a "gotta get this done so do the simplest thing first", aka. [YAGNI](https://en.wikipedia.org/wiki/You_aren't_gonna_need_it), decision than anything else so it's not carved in stone. It wouldn't be too much of an effort to change `Entity.registry` into a list of energy systems and automatically add newly constructed entities to all energy systems contained in `Entity.registry`.

I have to play grumpy old man though: this can get messy fast, so I'm *slightly* in favour of keeping track of entities belonging to different energy systems manually and instantiating energy systems with the corresponding entities as parameters:

```
  es1 = EnergySystem(first_entity_list)
  es2 = EnergySystem(sencond_entity_list)
```

The `add` method would only add an entity to a single energy system though.

Concerning the attribute "problem": I actually don't have an issue with that, since it suffices to have a constructor parameter like `track=list_of_energy_systems` where one can add the energy systems the entity should be added to explicitly. The empty list and `False` would mean that the entity isn't tracked at all and a value of `True` (the default) would mean that it is tracked in all currently known energy systems. No need to keep that information around as an attribute after construction so I'd be happy with something like that. :D

**Comment by simnh** [comment]
I am fine with manually instantiation in combination with the 'track' thing. So both should be possible. 
But I think `True` would mean that all entities created are added to the ONE energysystem, as it is an attribute of the es? Generally like the concept that this only works , until the next es is created (like it is now). 

The add method with a for loop is always an option.

**Comment by uvchik** [comment]
@simnh, @gnn What do think about a web-conference about these issues (#140, #139)?

I would prefer Tuesday or Friday afternoon.

**Comment by gnn** [comment]
@simnh , @uvchik A short TC sounds good to me. I'm fine with Tuesday and Friday after 13:00.

**Comment by uvchik** [comment]
For me after 14:00 better 14:30.

**Comment by simnh** [comment]
Tomorrow no....Friday I ll need to check

**Comment by gnn** [comment]
So, what's the verdict for friday? :)

**Comment by gnn** [comment]
Seems like this is a long standing issue and a rather complicated one. I'll postpone the decision for a course of action to the next release.

**Comment by gnn** [comment]
Aaaaand postponed. Don't want to decide this on a whim.

**Comment by jnnr** [comment]
Am I right or wrong? As I know it, components have to be added explicitly to an energysystem. As I understand, this has been decided sometimes. If this is the case I would like to close this one.

**Comment by uvchik** [comment]
I think this belongs to the "How do we see models, scenarios, energy-systems....". This is going to be an interesting section on the developer meeting :smile:

**Comment by jnnr** [comment]
Ok. I added it to the dev-meetings agenda and postpone it to v0.2.2.

**Comment by simnh** [comment]
thanks!

**Comment by p-snft** [comment]
I do not see any progress. Thus I tend to close the issue when nothing happens before the v0.3.1 release.

**Comment by uvchik** [comment]
It is possible to add an object to a specific EnergySystem so I think we can close this issue.
