### ISSUE TITLE
How to use VariableEfficiencyCHP-Transformer?

### ISSUE THREAD

**Issue by elisagaudchau** [oemof/oemof#167]
im confused about the VariableEfficiencyCHP-Transformer.
Docstring says:

```
   Parameters
     ----------
     eta_total : float
         total constant efficiency for the transformer
     eta_el : list
         list containing the minimial (first element) and maximal (second element)
         electrical efficiency (0 <= eta_el <= 1)

```
But these parameters seem to be unused:

...
```
         self.eta_total = sum(self.eta)
 
         # calculate minimal
         self.in_min = [self.out_min[0] / self.eta_min[0]]
         self.in_max = [self.out_max[0] / self.eta[0]]
 
         A = np.array([[1, self.out_min[0]],
                       [1, self.out_max[0]]])
         b = np.array([self.in_min[0], self.in_max[0]])
         self.coeff = np.linalg.solve(A, b)
```
...

Which parameters must be given?

**Comment by simnh** [comment]
Oh, well this is strange. But if you provide eta and eta_min it should give the correct result, unless you get an error, because eta_min is not set. 

Actually it should look like this: 

`self.in_min = [self.out_min[0] / self.eta_el[0]]
 self.in_max = [self.out_max[0] / self.eta_el[1]]`

I will fix this on master. 

eta_total will directly used in another constraint.

Note that this transformer will result in a mixed integer linear model. And you might want to check the results as it has not been tested a lot.
