### ISSUE TITLE
How to approve an external Pull request

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#18]
I would suggest that at least two developers should approve an external pull request. Even though more than two reviewers are named. That means two of them. If we are unsure we can name a reviewer in comment and ask for his/her opinion.

If it is an internal PR one reviewer should be enough.
 
@oemof/oemof-developer-group Do you agree?

**Comment by uvchik** [comment]
Here are examples:

PR 320 is approved by me so a second developer could merge it or approve it.
https://github.com/oemof/oemof/pull/320

For PR319 some changes are requested by me. In that case it shouldn't be merged without discussion even though two other developers approve it afterwards.
https://github.com/oemof/oemof/pull/319

**Comment by uvchik** [comment]
In the WebCo @gnn, @birgits, @beritRLI agreed.

**Comment by busiing** [comment]
Should this be written down in the docs? If so, where?
Is there any objection to close this issue?

**Comment by joroeder** [comment]
Properbly this was related to the long existing packages, eg solph, demand lib, .... I don't know how oemof.tabular, oemof.thermal wants to handle that. Generally, in my opintion, the proposal is good for all oemof repos - at least, I approve for all packages I am contributing so far.
I think this is not something for the documentation, rather for the Wiki, since it is kind of internal agreement. - So, this should be added in the wiki of the solph-package: [https://github.com/oemof/oemof-solph/wiki/Developer-notes-for-oemof-teams#how-to-review-and-merging-rules](https://github.com/oemof/oemof-solph/wiki/Developer-notes-for-oemof-teams#how-to-review-and-merging-rules)

btw, due to the unbundling, the oemof-solph wiki seems to need some clean-up anyway - some things can go to the docu, some to the oemof-solph wiki, some to the oemof-oemof wiki.

**Comment by busiing** [comment]
@joroeder if you think that might be an issue. Can you open a new one?

**Comment by joroeder** [comment]
I have put this information to the oemof-solph wiki [https://github.com/oemof/oemof-solph/wiki/Developer-notes-for-oemof-teams#how-to-review-and-merging-rules](https://github.com/oemof/oemof-solph/wiki/Developer-notes-for-oemof-teams#how-to-review-and-merging-rules). So, the results/agreement of this issue is noted somewhere, and I will close this issue. If there is anything against, please re-open this issue again.

For the other issues, I just mentioned above, of the docs of oemof-oemof and the general structure of oemof-solph, there are already two issues ([https://github.com/oemof/oemof/issues/69](https://github.com/oemof/oemof/issues/69), #67) - when things are sorted out there, we can directly implement and clean up the docs of both (solph and oemof in PRs).
