### ISSUE TITLE
Adding constraints

### ISSUE THREAD

**Issue by Jazzpilz** [oemof/oemof#182]
So far I know I can add constraints as parameters to oemof objects
(e.g. out_max for a maximum output) or I could define my own constraints
in linear_constraints.py or mixed_integer_linear_constraints.py in the
oemof.solph module.

With the new solph it should be possible to tell solph about new constraints.
Are the following example constraints already possible and if not, where
do you think is the best layer/place in oemof to start implementing it? 
Or is it necessary that I build such constraints in Pyomo and merge them 
with existing constraints in my oemof model?

```
solph.Storage(label="thermal",
capacity = ...,  # should be an integer variable
c_rate_in <= 0.4 * storage_capacity)

solph.Source(label="st",
output={bel: solph.Flow(actual_value= 0.5 * thermal.capacity)})

```
In case it is not yet possible to do add these kind of constraints 
directly, when will it be implemented (just for me to now for my project
schedule and how to cope with it)?

It would also be very great if you could load up a simple example,
illustrating how to cope with various constraint application scenarios
in the new solph structure (e.g. the two above).

As always, thanks a lot for the support.

**Comment by simnh** [comment]
I am not sure what you are trying to do, but I i'll try anyway: 

1.  We won't provide a way for users at object instantiation where they can pass " x >= 10" and we 'parse' this constraint
2. c_rate_in is a value that will bound the flow into the storage. In the refactored solph this 
    is named nominal_input_capacity_ratio. 

You will need to do (if you know thermal.capacity before optimization) :
```
solph.Source(label="st",
output={bel: solph.Flow(actual_value= 0.5, nominal_value=thermal.capacity)})
```

Otherwise: 

```
solph.Source(label="st",
output={bel: solph.Flow(actual_value= 0.5, investment=solph.options.Investment(maximum=10000)})
```

**Comment by simnh** [comment]
The c_rate is actually only used in the investment storage i just saw, so if you know your storage capacity 
just set the bounds inflow and outflow of the storage accordingly.

**Comment by simnh** [comment]
the block.py file in solph and their docstrings should help understanding what's going on.

**Comment by Jazzpilz** [comment]
Thank you for the explanation, it is good to know where you are heading
so I know where to invest my time in this respect.

Obviously it is good to have a decent amount of freedom when it comes to
constraints, could you point out how to declare a parameter of an object
as integer only (say I would like to restrict the capacity to integer
values in a range of 5-10)?

I guess so far I need to add those kind of constraints at a low level
and talk to pyomo directly, right?

**Comment by simnh** [comment]
If you want to set the 'range' of the capacity, that would imply setting upper and lower bounds of the 
associated capactiy variable in the optimization problem you can simply achieve this by this: 

```
solph.Storage(label="thermal",
nominal_capacity = 10, min=0.5, max=1) 
```

this will lead to bounds of  lb=10*0.5 and ub 10*1. Min and max may as well be array like, so that in every timestep of the problem there can be different bounds.  If a scalar is provide it will automatically converted to a array of length of the optimization problem. 

Note, that integer values are not possible at the moment. It could be easily implemented, if you just copy the Storage class from 'blocks.py' and set the attribute of the pyomo `Var` class
(L69)
```
self.capacity = Var(self.STORAGES, m.TIMESTEPS,
                               bounds=_storage_capacity_bound_rule,  within=po.NonNegativeIntegers)

This will however result in a MILP problem, which will significantly increase your runtime of the problem
```

**Comment by Jazzpilz** [comment]
Thank you, that helped me a lot!
