### ISSUE TITLE
Issues with solph.Storage

### ISSUE THREAD

**Issue by Jazzpilz** [oemof/oemof#194]
Generally when working with the solph.Storage class I face issues when I define a storage as non-investment object, as e.g.:

```python
    solph.Storage(
        label='storage',
        inputs={bel: solph.Flow(variable_costs=10e10)},
        outputs={bel: solph.Flow(variable_costs=10e10)},
        capacity_loss=0.00, initial_capacity=0,
        nominal_input_capacity_ratio=1/6,
        nominal_output_capacity_ratio=1/6,
        inflow_conversion_factor=1, outflow_conversion_factor=0.8,
        fixed_costs=35
    )
```
This throws the error:

`  bounds = (n.nominal_capacity * n.capacity_min[t],
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'`

However I see no reason why the above specification should not work. What is the reason for this? For me it only works to get instances of the Storage class to work when specifying them as investment objects, as for example in the storage_invest example.

**Comment by uvchik** [comment]
You haven't defined the size of the storage. If you use the investment mode the optimal size of the storage is determined by the solver. If you do not use the investment mode the size of the storage is static you have to define it using the `nominal_capacity` attribute. If you do not define it, the nominal_capacity will be `None` and that's why the multiplication (nominal_capacity * capacity_min) does not work according to you error message.

The following code should work:

```python
    solph.Storage(
        label='storage',
        inputs={bel: solph.Flow(variable_costs=10e10)},
        outputs={bel: solph.Flow(variable_costs=10e10)},
        nominal_capacity=1000,
        capacity_loss=0.00, initial_capacity=0,
        nominal_input_capacity_ratio=1/6,
        nominal_output_capacity_ratio=1/6,
        inflow_conversion_factor=1, outflow_conversion_factor=0.8,
        fixed_costs=35
    )
```

**Comment by Jazzpilz** [comment]
Thank you, seems I have missed the obvious!

**Comment by uvchik** [comment]
Please close this issue if everything works right now.
