### ISSUE TITLE
Make installation of CBC easier

### ISSUE THREAD

**Issue by gplssm** [oemof/oemof#198]
I noticed that cbc is the default solver for examples in branch release/v0.1. If I start with oemof from scratch I run into the error that not cbc executable can be found.

Make it first-time users easier to run examples
1. Make requirement explicit in the docs. Either in [the installation section](http://oemof.readthedocs.io/en/release-v0.1/getting_started.html#installing-oemof) or the [examples section of the readme](https://github.com/oemof/oemof#examples) to let the user know that cbc is required to run examples
2. To prevent new users from manual installation of external libraries (here cbc) make cbc a dependency of oemof. Maybe [cylp](https://github.com/coin-or/CyLP) could be helpful here if applicable.

**Comment by uvchik** [comment]
1. We could divide the example section of the readme in subsections (solph...) and add the coin-or link there, because it is only needed for the solph examples (https://projects.coin-or.org/Cbc). Beyond the README-file there already exists a paragraph about solvers in the [using oemof](http://oemof.readthedocs.io/en/release-v0.1/using_oemof.html#oemof-solph) section.
2. As I understand it cylp is not needed. The CBC solver has to be installed but the python binding works through pyomo.

**Comment by gplssm** [comment]
You're right, installation of CBC is sufficiently described within Pyomo install instruction.
