### ISSUE TITLE
Add NodesFromCSV example to oemof solph examples

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#208]
After we pulled renpassG!S out of the repo, we should provide a simple csv-input example for the use 
of the csv reader.

**Comment by simnh** [comment]
I started adding an example...

**Comment by ckaldemeyer** [comment]
:+1 I'll come to that next week

**Comment by ckaldemeyer** [comment]
See: https://github.com/oemof/oemof/pull/223

Do you think it's o.k. like this?

**Comment by ckaldemeyer** [comment]
Btw: Should we agree on a "style" to provide examples or let them be heterogenously? Some are now wrapped in functions and some straightforward. Just as an idea. I personally do not mind..

**Comment by uvchik** [comment]
Examples do have two functions:

1. Illustrate users how features work.
2. Test oemof

To test oemof using the results I created `example_tests.py` some time ago. This file executes all existing examples and check whether they run correctly. To check if they run correctly some results are produced and compared with stored results. Before merging a PR this test file should run without errors.

To run your example and get some results back it has to be a function.

I also integrated the nosetests, so that it is now a full test. Therefore I renamed it to `oemof_full_test.py`

With commit 787ce0de7 I integrated the example of @simnh without results. But I highly recommend to add results checks as well. We already had some tests in the past where the run-check was okay but the results were different.

@ckaldemeyer, @simnh : Will you be able to return a result dictionary with you examples?

**Comment by ckaldemeyer** [comment]
Thanks for your explanation. You're right that it should be fully integrated in a test using results.

But I won't be able to make it for this release since I want to check the documentation and contribute to the paper this week.

**Comment by ckaldemeyer** [comment]
> @ckaldemeyer, @simnh : Will you be able to return a result dictionary with you examples?

What does it have to contain? Some time series and a flag? If I just have to create a dict it should be possible within this week. But looking into how to integrate it into a test would take me longer.

**Comment by uvchik** [comment]
If your example returns a result-dict, I will do the integration. Okay?

**Comment by ckaldemeyer** [comment]
I'll create one!

**Comment by ckaldemeyer** [comment]
Done. Thanks in advance!

**Comment by uvchik** [comment]
I had to change your example a little to make it suitable for the tests. Please have a look if it is okay for you like this.

You should definitely use the absolute path otherwise it is not possible to execute the example from somewhere else (compare #212).

```
# This works with relative path and absolute path
cd path/to/examples
python3 your_example.py

#This does not work with relative path but with absolute path
python3 path/to/examples/your_example.py
```

BTW: The plotting line is commented out. Is it intended like this? I did not change it.

**Comment by simnh** [comment]
I did not look at the example, but generally I think we should have example that are as simple as possible to allow easy access for new users. From my perspective this means we should not force every example to be compatible with tests as we need to wrap everything in functions etc....

**Comment by uvchik** [comment]
In my opinion the example is not more difficult to understand if it is wrapped into functions. The  difference is quite small:

```python
import oemof

a = 1 + 5
b = a * 3
```

```python
import oemof

def run_example()
    a = 1 + 5
    b = a * 3

if __name__ == "__main__":
    run_example()
```

And as we all quite lazy in writing test the examples are a good way to have most parts tested.

**Comment by ckaldemeyer** [comment]
> You should definitely use the absolute path otherwise it is not possible to execute the example from somewhere else (compare #212).

I forgot about that. Thanks for the hint and the adaptions. I am fine with it!

> BTW: The plotting line is commented out. Is it intended like this? I did not change it.

I wasn't sure about it since the example should just illustrate the funtionality. I'll uncomment it.

Thanks.

**Comment by ckaldemeyer** [comment]
I had an error with the file path (redundant folders):

"OSError: File b'/home/cord/Programmierung/oemof/examples/solph/csv_reader/operational_example/solph/csv_reader/operational_example/scenarios/example_energy_system.csv' does not exist"

Just fixed it with the plot!

**Comment by uvchik** [comment]
Sorry, that was my fault.
