### ISSUE TITLE
solph.GROUPINGS as default parameter

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#214]
The solph library does not work properly if `solph.GROUPINGS` is not passed to the `solph.EnergySystem`. Shouldn't we set the solph.GROUPINGS by default for the `solph.EnergySystem`?

**Comment by simnh** [comment]
I think we could do this ...

**Comment by simnh** [comment]
It not as easy as i assumend. For now I added a Error message. If @gnn wants to fix it, he may do it...

**Comment by uvchik** [comment]
It was not a big deal but I had to move the EnergySystem to the groupings module to avoid a circular import. Therefore I renamed `groupings.py` to `system.py` to make it less confusing, that it is now more than just a grouping module. Please add comments at PR #215.

**Comment by gnn** [comment]
Ok, I finally was able to wrap my head around what's happening here. The reason for the fact that solph's `GROUPINGS` are not used by default when instantiating solph's `EnergySystem` had to do with the following problem: what if the user wants to supply his own groupings? Previously he could change `EnergySystem(groupings=GROUPINGS)` to `EnergySystem(groupings=GROUPINGS + CUSTOM_GROUPINGS)` or explicitly switch off solph's `G`s if he knew what he was doing.
Now, if a user starts using just `es = EnergySystem()` and decides to change that to `es = EnergySystem(groupings=CUSTOM_GROUPINGS)`, the behavior of `es` changes drastically, as `GROUPINGS` gets switched off implicitly, which might be very surprising. So IMHO most of the time a user has to go for `EnergySystem(groupings=GROUPINGS + CUSTOM_GROUPINGS)`, but he doesn't really know that because we are "hiding" `GROUPINGS` from him in the default argument.
And if we always prepend `GROUPINGS` to the value of the `groupings` keyword argument, we are taking the option of switching off `GROUPINGS` away from the user.
That means the question is which option we prefer.
In any case I will add a (hackish) solution for the variant presented here which doesn't move `EnergySystem`, tomorrow. I'd like to keep it in network, cause I actually want it to be in network in core to. I really think `EnergySystem` belongs into the network module.

**Comment by simnh** [comment]
thanks for clarifying!

**Comment by uvchik** [comment]
Yes, thanks.

For me the groupings function is advanced stuff. I think users can use solph properly without understanding the inside of solph unless they understand what constraints are build. The do not have to understand how. For these users I would try to lower the entry barrier and avoid confusing stuff.

Advanced users might want to add own groups. These users have to understand the grouping-concept and these users have to understand how to add groups and blocks. So what are the typical cases.

In the default case the user does not want to do anything. In a second case the user wants to add something and in a third case the user wants to replace the default groupings with his/her own stuff.

One approach could be to add two optional parameters (*add=CUSTOM_GROUPINGS*, *replace=CUSTOM_GROUPINGS*).

@gnn These are just ideas. If you think it is to hacky, leave at as it is. I can live with the actual state as well.

**Comment by gnn** [comment]
I went with the "always use/prepend `solph.GROUPINGS` approach. See the pull request. The class docstring now clearly states what is happening and what to do if differing behavior is desired. In case solph's `EnergySystem` gains additionally functionality so that using core's version is no longer an option, we can always add `keep_default_groupings=True` (or `remove_groupings=[]`) or something similar as an additional keyword argument.
I totally forgot to add a whatsnew note. Gonna do that right now.

**Comment by uvchik** [comment]
PR #215 is merged.
