### ISSUE TITLE
Example simple_least_costs not working properly?

### ISSUE THREAD

**Issue by fwitte** [oemof/oemof#240]
I tried to run the provided example file under modified constraints, e.g. by changing the conversion factors, and I always get the same result. Also, the problem gets infeasible, if I change one conversion factor to zero.
Though, changing the energy prices influences the results in a reasonable way.

Greetings

Francesco

**Comment by ckaldemeyer** [comment]
By "results" you mean the objective, I guess.

**Comment by fwitte** [comment]
The dispatch and thus the objective are not affected by the changes.

**Comment by uvchik** [comment]
Not every change in the system has to affect the results, so it is hard to say without knowing what exactly you have done. 

The easiest way to debug energy models is to create a simple system with obvious results. If this works you can step by step add components. Be aware that it might be necessary to add slack or excess components.

**Comment by ckaldemeyer** [comment]
I tried it myself:

1.) Original Parametrization (conversion_factors={b_el: 0.5}):

    	LinearTransformer(label='pp_gas',
                      inputs={bgas: Flow()},
                      outputs={b_el: Flow(nominal_value=41,
                                          variable_costs=40)},
                      conversion_factors={b_el: 0.5})

yields

		{'objective': 2947725.1748075034,
		...
		 ('b_el', 'to_bus', 'pp_gas', 'val'): 30412.376282889993,
		...
		 ('gas', 'from_bus', 'pp_gas', 'val'): 60824.752565779985,
		...
		}

2.) Changed Parametrization (conversion_factors={b_el: 0.001}):

	    LinearTransformer(label='pp_gas',
		              inputs={bgas: Flow()},
		              outputs={b_el: Flow(nominal_value=41,
		                                  variable_costs=40)},
		              conversion_factors={b_el: 0.001})

yields

		{'objective': 2947725.1748075034,
		...
		 ('b_el', 'to_bus', 'pp_gas', 'val'): 30412.376282889993,
		...
		 ('gas', 'from_bus', 'pp_gas', 'val'): 30412376.282890026,
		...
		}

So, as one would expect, by decreasing the efficiency of the gas powerplant, more of the resource is needed in order to provide the same amount of electricity/have the same dispatch.

But the overall system costs are not affected as the objective remains the same. So I thought that this is not the case because the resource itself does not have a price.

But even changing the resource price to some value, e.g.

        bgas = Bus(label="gas", balanced=False, variable_costs=50)

does not change the objective.

But it should, doesn't it?

Maybe I am blind but I don't see the error at the first glance..

**Comment by uvchik** [comment]
> Maybe I am blind but I don't see the error at the first glance..

I think I do and that is the reason why I do not like this way of modelling. It works if you know what you are doing but it is not obvious.

The normal way would be to create a balanced bus (your gas bus is unbalanced) and add a gas source. This gas source should have a price. Then the cost will increase if the efficiency is lower.

I guess @simnh wanted to make a short example. He accumulated the gas costs to the variable costs of the power plant. He did not create a gas source and therefore set a Bus to unbalanced (balanced=False). The variable costs are now connected to the efficiency and you have to change the costs if you change the efficiency. It is not obvious how to change them because they contain the variable costs of the power plant **and** the fuel costs. I personally do not like this way of modelling even though you have to define no gas source.

Solph is flexible and you can do a lot but you definitely should know what you are doing.

I complained about this way of modelling a year ago but we decided to leave solph more flexible. As this is an example we should think of modelling more explicite to make it easier for newcomers to understand it. Or we can show that there are different modelling philosophies but we should describe it.

**Comment by uvchik** [comment]
@ckaldemeyer You cannot set `variable_costs` to a Bus. It will have no effect, even though solph will not complain due to  the `**kwargs` option.

**Comment by ckaldemeyer** [comment]
> The normal way would be to create a balanced bus (your gas bus is unbalanced) and add a gas source. This gas source should have a price. Then the cost will increase if the efficiency is lower.

Actually, that was what I intended to do but somehow I just gave a price to the bus..my mistake. But thanks for clarifying!

> I complained about this way of modelling a year ago but we decided to leave solph more flexible. As this is an example we should think of modelling more explicite to make it easier for newcomers to understand it. Or we can show that there are different modelling philosophies but we should describe it.

I agree!

By the way, my error trial

    bgas = Bus(label="gas", balanced=False, variable_costs=50)

did not throw up any messages, etc. 

Maybe we can just add error messages e.g. "The bus contains variable costs. Is it intended to ... ?" or as you said just illustrate the "modelling philosophies" which would be my favorite option.

**Comment by ckaldemeyer** [comment]
> @ckaldemeyer You cannot set variable_costs to a Bus. It will have no effect, even though solph will not complain due to the **kwargs option.

You were faster than me. Yes, this was the reason..

**Comment by ckaldemeyer** [comment]
I have extended the "Example Streamlining Issue" so we check everything for explicit modelling and add some comments, too.

@fwitte : You can close this issue if you are fine with the answer.

**Comment by uvchik** [comment]
You could define the 'variable_costs` in the input flow of the transformer.

**Comment by fwitte** [comment]
Thank you very much, everything works as expected after introducing sources for coal, lignite, gas and oil.
Have a nice week!
