### ISSUE TITLE
Enable real slicing via DateTimeindex in CSV-reader

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#258]
Description in https://github.com/znes/renpass_gis/issues/18

**Comment by s3pp** [comment]
Maybe slicing should only be available if the first column in nodes_flows_sequences contains a format compatible with pd.to_datetime(). Otherwise I think an implementation of slicing functionality using date ranges would be prone to errors, because there is no clean "base" DateTimeindex to slice on.

**Comment by ckaldemeyer** [comment]
> Maybe slicing should only be available if the first column in nodes_flows_sequences contains a format compatible with pd.to_datetime(). Otherwise I think an implementation of slicing functionality using date ranges would be prone to errors, because there is no clean "base" DateTimeindex to slice on.

I agree. This also complies with doing things explicit without "hidden magic". We could discuss this when we start. I am thinking about two oemof-dev-days in your office next week to implement my issues ;)
