### ISSUE TITLE
Making oemof citable

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#264]
Should we make oemof's major versions citable? 

https://guides.github.com/activities/citable-code/

**Comment by uvchik** [comment]
We should, but what is the simplest way? 

Do you think it's Zenodo? For me figshare looks simple, too. In my opinion OSF is a little too musch for just getting an DOI.

- https://mozillascience.github.io/code-research-object/
- https://osf.io/

**Comment by uvchik** [comment]
Zenodo is fine. Go ahead if nobody else objects.

**Comment by ckaldemeyer** [comment]
> I agree you on osf... @gplssm proposed the github link above...why not use githubs proposal for github repository?
> Zenodo is fine. Go ahead if nobody else objects.

I have just read a bit around Zenodo, figshare and OSF and a lot of blog posts etc. for comparisons were outdated. Personally I don't mind too much except that we have already started with OSF for renpassG!S and it's scenarios (see below) and I don't like switching horses with every project when I don't see serious advantages/disadvantages.

* renpassG!S: https://osf.io/rz7fq/
* scenarios: https://osf.io/kp4mh/

With OSF I quite like the possibility to browse projects per user, to see the log for github repositories, to have analytics, and different proposals for citations.

One thing that might be a problem and I haven't thought about is how to deal with new releases, etc. The ideal way would be to have one citing option (including a DOI) per release, so in OSF terminology different DOIs per project.

This might be possible by forking the project and creating a new one: https://osf.io/kp4mh/forks/

If it is possible in an easy manner, I would vote to stick with OSF since it's a bit more comprehensive and we have already started..

Does anyone know how to deal with this issue or has some experience here?

**Comment by simnh** [comment]
The only thin we have to check is how we can make 'oemof-developing group' as a 'authors' because one person should not be the 'first' or 'corresponding author' of this project...but we can use osf...I don't care.

Regarding the versions, I it would be great to have one project, but new DOIS for every version, so nested projects kind of would be nice. Somebody needs to check this out. 

BTW: An other great thing about ost is that you can link your preprints to a certaint project

**Comment by ckaldemeyer** [comment]
+1 for OSF would be to link different storage types and provide links for zotero, etc.

**Comment by ckaldemeyer** [comment]
+1 for OSF due to project pages and notification options

**Comment by simnh** [comment]
I also created a project for testing purposes, I will invited others, so that we can experiment with osf on how to use this with oemof (its private for now anyway) 

https://osf.io/dwz7m/

**Comment by ckaldemeyer** [comment]
I think what we need should be possible with a registration (also needed for DOIs) which I forgot for the abovementioned projects:

#######

Registration creates a frozen version of the project that can never be edited or deleted but can be withdrawn. Your original project remains editable but will now have the registration linked to it. Things to know about registration:

Ensure your project is in the state you wish to freeze before registering.
Consider turning links into forks.
Registrations can have embargo periods for up to four years. If you choose an embargo period, the registration will automatically become public when the embargo expires.
Withdrawing a registration removes the contents of the registrations but will leave behind a log showing when the registration was created and withdrawn.

Continue your registration by selecting a registration form:

#######

I'll report more in a while..

**Comment by ckaldemeyer** [comment]
So in OSF terminology we need multiple registrations per project..

**Comment by simnh** [comment]
yes that would be great!

**Comment by simnh** [comment]
One option could be: 

oemof as as 'project' inside osf and than for every oemof version an own 'software' project...then we can link the software projects to the oemof project... 

but its still an overkill of projects I think

**Comment by ckaldemeyer** [comment]
I have now made two test registrations: https://osf.io/dwz7m/registrations/

But somehow there's no option to create a DOI/ARK for me in this project. Do I have the rights?

**Comment by ckaldemeyer** [comment]
I have sent an e-mail to the OSF support team:

####

Hi,

we are developing a free and open software framework to model energy supply systems across different institutes [1]. Meanwhile we have published 14 releases [2] with a changing developer and contributor base.

Since this base of developers and contributors is changing quite frequently it would be helpful to create one citation (including a DOI/ARK) per release that only includes the people who contributed.

What would be the recommended way to implement this in your service? Should we use sub-projects (which seems a bit heavy handed) or is there another option?

Best wishes and thanks in advance,
Cord Kaldemeyer

[1] https://github.com/oemof/oemof
[2] https://github.com/oemof/oemof/releases

**Comment by uvchik** [comment]
I am just afraid of another structure to maintain. There is another wiki tab. We do not have to fill it but it does not look good if its empty. We just decided to revise our website and we haven't finished.

oemof on the web:

- github
- pypi
- wordpress
- readthedocs

Zenodo seems to be limited to the DOI and nothing else.
https://zenodo.org/search?page=1&size=20&q=pvlib&sort=mostrecent

**Comment by ckaldemeyer** [comment]
The option to assign single contributors is obsolete here but it would be cool for other projects.

Another idea: We could also link the release notes in the documentation or the github activity on OSF..

**Comment by ckaldemeyer** [comment]
> I am just afraid of another structure to maintain.

I see your point.

> There is another wiki tab. We do not have to fill it but it does not look good if its empty.

I have just deactivated the wiki and now it's hidden.

> We just decided to revise our website and we haven't finished.
>
> oemof on the web:
>
> - github
> - pypi
> - wordpress
> - readthedocs

For me, this would be one more reason to have one central point to land (which could be OSF).

**Comment by ckaldemeyer** [comment]
> For me, this would be one more reason to have one central point to land (which could be OSF).

But we could also just use it like Zenodo..

**Comment by ckaldemeyer** [comment]
Anyway, we can just wait for the answer and see how it could work in their recommended way. If it's complicated I have no objections against Zenodo or something else..

**Comment by uvchik** [comment]
We just decided to make worpress the central point to land just a month ago.

**Comment by uvchik** [comment]
If we keep osf streamlined it is okay for me.

**Comment by ckaldemeyer** [comment]
> We just decided to make worpress the central point to land just a month ago.

Yes, you're right. I agree, no new construction sites are needed..

> If we keep osf streamlined it is okay for me.

One simple solution I just had: We could also just add a template-marker for the version number in the project description, e. g.:

"oemof Developing Group. (2017, January 2). Open Energy Modelling Framework (oemof) - A modular open source framework to model energy supply systems. Version #put-your-used-version-number-here. Retrieved from osf.io/dwz7m"

So if someone cites oemof based on OSF, the date and version always progress. And it's clear which version is linked. Additionally one could link the releases on github..

By going this way, we wouldn't even have to archive repos, etc. with new releases.

**Comment by ckaldemeyer** [comment]
And if oemof is cited without using a specific number it is just left out..

**Comment by simnh** [comment]
I like the 'template' idea, In this way everyone is responsible to check which version he/she is citing. 

I also think that we can oemof.org as a 'static' info page and take osf for more comprehensive stuff (link to other osf-projects. storages, preprints) easily...

**Comment by uvchik** [comment]
Sounds good. In that case you could also do the following.

"oemof Developing Group. (2017, January 2). Open Energy Modelling Framework (oemof) - A modular open source framework to model energy supply systems. **Commit #23af3456.** Retrieved from osf.io/dwz7m"

Then we should connect osf to github, as we did in the test page [long time ago](https://osf.io/7q4kg/).

**Comment by uvchik** [comment]
It might be interesting to reactivate the wiki for a static informations:

Sense of this page and where you can find the rest.

**Comment by gplssm** [comment]
As you are actually resolving it, I assigned you. Thx, Cord!

**Comment by ckaldemeyer** [comment]
> As you are actually resolving it, I assigned you. Thx, Cord!

So far, we are just waiting for the mail from OSF ;-) I would say that the deadline for a decision  is next Monday (the 9th).

**Comment by ckaldemeyer** [comment]
If everybody is fine..

**Comment by uvchik** [comment]
> I would say that the deadline for a decision is next Monday (the 9th).

Are both types okay for you?

**Stable version:** 
oemof Developing Group. (2016, November 2). Open Energy Modelling Framework (oemof) - A modular open source framework to model energy supply systems. Version v0.1.1. Retrieved from osf.io/dwz7m

**Developer version:**
oemof Developing Group. (2016, November 23). Open Energy Modelling Framework (oemof) - A modular open source framework to model energy supply systems. Commit 6c451c4c7f. Retrieved from osf.io/dwz7m

I think the date should be the date of the version/commit.

**Comment by ckaldemeyer** [comment]
I would be fine with it!

**Comment by gplssm** [comment]
In the context of oemof potentially will be discussed in research paper, I talked with Simon about this Issue. We agreed on that we would like to have a DOI (as per version of oemof) by next Monday (January 23th). 

I don't know what is the current status of the discussion with OSF. Maybe you can provide an update, @ckaldemeyer? If this does not seem to work soon, I suggest to setup zenode-github integration next Monday (maybe Tuesday if it takes long) and generate DOIs.
This would not take the opportunity to switch to OSF referencing service on the long run as we can deactivate the zenodo or even have two parallel systems.

If there are concerns about the next steps I suggested, please let us know. But I would like to finish discussion here and get a result of it.

**Comment by ckaldemeyer** [comment]
> I don't know what is the current status of the discussion with OSF. Maybe you can provide an update, @ckaldemeyer? If this does not seem to work soon, I suggest to setup zenode-github integration next Monday (maybe Tuesday if it takes long) and generate DOIs.

I did not get an answer yet but from my side there is nothing that speaks against OSF as @uvchik s suggestions:

> Are both types okay for you?
> 
> Stable version:
> oemof Developer Group. (2016, November 2). Open Energy Modelling Framework (oemof) - A modular open source framework to model energy supply systems. Version v0.1.1. Retrieved from osf.io/dwz7m
> 
> Developer version:
> oemof Developer Group. (2016, November 23). Open Energy Modelling Framework (oemof) - A modular open source framework to model energy supply systems. Commit 6c451c4. Retrieved from osf.io/dwz7m

seem to be o.k. for me and there have not been any objections from you, @simnh and others.

This would work for oemof as for our first scenarios published on OSF (https://osf.io/rz7fq/) and if you lookup the DOI at http://www.doi.org you (of course) end up at OSF where the respective citation options are shown.

For me this would be perfect!

> If there are concerns about the next steps I suggested, please let us know. But I would like to finish discussion here and get a result of it.

I was just waiting for your reaction :-)

**Comment by simnh** [comment]
I think there is no real difference between ost and Zenodo but is that osf has a overhead, we do not need for all other projects. basically all oemof code and oemof based apps are hosted on github, so why don't we just go with zenodo as proposed by them? 

As @gplssm  said, we want the DOI for v.0.1.1 next week and we propose zenodo as I think this is the light weight version of osf....

I there are objections from your side @ckaldemeyer , please discuss with @gplssm  and close the issue with the decision made bilaterally...

**Comment by ckaldemeyer** [comment]
> I think there is no real difference between ost and Zenodo but is that osf has a overhead, we do not need for all other projects. basically all oemof code and oemof based apps are hosted on github, so why don't we just go with zenodo as proposed by them?
> 
> As @gplssm said, we want the DOI for v.0.1.1 next week and we propose zenodo as I think this is the light weight version of osf....
> 
> I there are objections from your side @ckaldemeyer , please discuss with @gplssm and close the issue with the decision made bilaterally...

I thought we go with OSF as we have already started with renpassG!S and the scenarios and OSFs "overhead" doesn't have to be used and it not a disadvatage.

To be honest I don't really mind but would tend to stick with OSF as it works and we have to registrate again for Zenodo, etc.

Like in many discussions we had: why should we open a new barrel/switch horses when we have a working solution?

I don't see any real advantages for Zenodo except that it might be a bit more lightweight and is recommended by github..

**Comment by ckaldemeyer** [comment]
@gplssm You can decide this if you want.

**Comment by ckaldemeyer** [comment]
A bit late but here's the answer from OSF:

#####

Hi Cord,
I am SO sorry for the slow reply! This got lost in my shuffle.

I think the best way to accomplish this would be to create a registration (frozen, time-stamped version of a project at one point in time). Each registration has its own persistent, globally unique identifier and can also have its own DOI. Then you can continue to update the main project (change contributors, add new code, etc.) but keep snapshots along the way.

Here’s a help article that explains more about registrations: http://help.osf.io/m/registrations/l/524205-register-your-project

Please don’t hesitate to reach out with additional questions or feedback.

Best,
Sara

on my initial mail:

#####

Hi,

we are developing a free and open software framework to model energy
supply systems across different institutes [1]. Meanwhile we have
published 14 releases [2] with a changing developer and contributor base.

Since this base of developers and contributors is changing quite
frequently it would be helpful to create one citation (including a
DOI/ARK) per release that only includes the people who contributed.

What would be the recommended way to implement this in your service?
Should we use sub-projects (which seems a bit heavy handed) or is there
another option?

Best wishes and thanks in advance,
Cord Kaldemeyer

[1] https://github.com/oemof/oemof
[2] https://github.com/oemof/oemof/releases

**Comment by ckaldemeyer** [comment]
As I said, just go ahead @gplssm

**Comment by ckaldemeyer** [comment]
@gplssm Have you decided anything? ;)

**Comment by uvchik** [comment]
I lost the thread. Shall we vote for either OSF or Zenodo? Do we already have an DOI since January 23 already passed by?

**Comment by ckaldemeyer** [comment]
I am still waiting for @gplssm s answer

**Comment by gplssm** [comment]
I'm sorry, I totally forgot this. Here it is  [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.276054.svg)](https://doi.org/10.5281/zenodo.276054)

**Comment by ckaldemeyer** [comment]
Thanks!

I am not sure why the following names are on the list:

* Steffen Peleikis (was involved for 3 months in 2014)
* Wolf-Dieter Bunke
* Elisa Papadis
* Elisa Gaudchau
* Christian Fleischer

and why the following ones are not:

* Martin S. (@s3pp)

Did you derive it from the [activity graph](https://github.com/oemof/oemof/graphs/contributors)?

I would rather keep it to major contributions from my opinion!

**Comment by gplssm** [comment]
Yes, I took the activity graph/contributors list.

If we have a better rationale for choosing contributors/authors, let's take this!

@s3pp isn't on the contributors list, thus he isn't in the author list.

I'm open for suggestions!

**Comment by ckaldemeyer** [comment]
> @s3pp isn't on the contributors list, thus he isn't in the author list.

I don't understand why because he also contributed some stuff to the outputlib and csv-reader. Is it possible to hide contributions from repos?

> If we have a better rationale for choosing contributors/authors, let's take this!

This is really difficult from my opinion since commits/code lines are a necessary criteria from my opinion but only measure quantity and one could also make many very small commits and push a csv-file to pimp the statistics.

On the other hand conceptual contributions in any form -which are not measurable- and often slurry are also not enough from my point of view.

> I'm open for suggestions!

From my opinion something like an anonymous vote where a person needs X of Y possible votes from the group to be added (having a deadline) would be suitable because the people who develop and take part probably best know who was working on the project and who was not.
This would also be a tool for other projects such as papers, etc.

Another idea would be to just post individual opinions and discusss it in issues like here openly.

But it might be a bit too much for such a list..

**Comment by uvchik** [comment]
If your account is not correctly connected you will be able to commit anonymously (see 40a285c4fd). If your commits are not part of the history of the master you won't be part of the contributors list.

But as I understand @ckaldemeyer this is not the main point anyway. It is very difficult to measure the contribution to the oemof project because there are so many ways to push oemof forward. I think the first four people in the list are the main code writer but this does not necessarily means that they are the main contributor to the overall project.

The main problem is that the idea of open source and collaborative working meets the world of ranking and scientific reputation. Otherwise we would not care about the order. We already had the discussion when we talked about publications and author lists.

We may want to talk about this in a web conference. 

I think it is a good idea to make a web conference, anyway.

**Comment by ckaldemeyer** [comment]
> The main problem is that the idea of open source and collaborative working meets the world of ranking and scientific reputation. Otherwise we would not care about the order.

:+1: 

For me it is important to not offend anybody and it's not about having someone definetely not on the list. It's just about how to deal with this because the list cannot grow endless and as I said we have to discuss about very minor or contributions from very long ago. One criteria could also be if people react or have been active on github at all within periods of months.

> We may want to talk about this in a web conference.
> 
> I think it is a good idea to make a web conference, anyway.

:+1:

**Comment by ckaldemeyer** [comment]
Any news here? If no one is interested I would suggest that @uvchik and me make a  proposal and we can discuss it with a deadline.

**Comment by ckaldemeyer** [comment]
https://github.com/oemof/oemof/issues/275

**Comment by ckaldemeyer** [comment]
> I'm sorry, I totally forgot this. Here it is

Now we have the DOI but in #275 we had the discussion about which authors occur and further up here we basically agreed on the following:

> Are both types okay for you?
> 
> Stable version:
> oemof Developer Group. (2016, November 2). Open Energy Modelling Framework (oemof) - A modular open source framework to model energy supply systems. Version v0.1.1. Retrieved from osf.io/dwz7m
> 
> Developer version:
> oemof Developer Group. (2016, November 23). Open Energy Modelling Framework (oemof) - A modular open source framework to model energy supply systems. Commit 6c451c4. Retrieved from osf.io/dwz7m

But Zenodo (https://zenodo.org/record/276054#.WNpLFN8yqy8) now says:

    Cite as
    Uwe Krien, Simon Hilpert, Cord Kaldemeyer, Stephan Günther, Caroline Möller, Guido Pleßmann, …     Christian Fleischer. (2016). oemof v0.1.1 [Data set]. Zenodo. http://doi.org/10.5281/zenodo.276054

**Comment by ckaldemeyer** [comment]
Whats's now the right way to cite oemof? I came across this because @fraukewiese asked me how to cite renpassG!S because they're searching for a way to cite the Balmorel model.

**Comment by gplssm** [comment]
I did it, see #299 
Citation now is:
oemof Developer Group. (2017). Open Energy Modelling Framework (oemof) - A modular open source framework to model energy supply systems. Version v0.1.4 [Data set]. Zenodo. http://doi.org/10.5281/zenodo.438676

Hope you're fine with it!

Do will still need the v0.1.1 and v0.1.2 zenodo citation?

**Comment by uvchik** [comment]
> Do will still need the v0.1.1 and v0.1.2 zenodo citation?

As we do have backward compatibility within v0.1.x citing a lower version shouldn't be necessary.
