### ISSUE TITLE
Calculation time - with more than one demand in the energy system

### ISSUE THREAD

**Issue by Benedikt4** [oemof/oemof#291]
Hi,
i have a question about the time to solve a problem. I built an electricity energ ysystem with 6 busses. Every bus has an easy input. And bus 1 is connected to bus 2 in both direction (2 transformsers). Bus 2 is connected to bus 3 on the same way. …. bus 6 is connected to bus 1. So it is a ring structure. Every bus has a sink.
The bus 1 is also connected with a gas bus by an gas power plant. The gas bus has 1 input with energy. 
Now I started to connect one demand on bus 1 with 8760 time steps (one year). I let the program solve the flow of every object in this energysystem. I got the solution after 40 seconds. 
But my goal is to solve the problem with more demands in the system. So I integrated a second demand on bus 2. Now the calculation time was about 3 minutes. With an third demand on bus 3 the calculation time was 15 minutes. And with a demand at every bus, it takes more than 40min.

My processor is an i5 4670K 3.4 GHz.

My problem is: Why the CBC solver needs so much time to solve the problem with more demands in the energysystem? Is there any reason?

Do you now how the solver exactly works? I couldn’t find any answer. 
If you have any idea or link for me – I prefer a website in german  thank you for your help.

**Comment by ckaldemeyer** [comment]
> Hi,
> i have a question about the time to solve a problem. I built an electricity energ ysystem with 6 busses. Every bus has an easy input. And bus 1 is connected to bus 2 in both direction (2 transformsers). Bus 2 is connected to bus 3 on the same way. …. bus 6 is connected to bus 1. So it is a ring structure. Every bus has a sink.
> The bus 1 is also connected with a gas bus by an gas power plant. The gas bus has 1 input with energy.
> Now I started to connect one demand on bus 1 with 8760 time steps (one year). I let the program solve the flow of every object in this energysystem. I got the solution after 40 seconds.
> But my goal is to solve the problem with more demands in the system. So I integrated a second demand on bus 2. Now the calculation time was about 3 minutes. With an third demand on bus 3 the calculation time was 15 minutes. And with a demand at every bus, it takes more than 40min.

Could you provide some output details such as the solver stream which gives you the solution method and problem size (matrix)?

> My problem is: Why the CBC solver needs so much time to solve the problem with more demands in the energysystem? Is there any reason?

Your problem seems to be purely linear I am guessing CBC uses the SIMPLEX method to solve it. In this case "However, the simplex algorithm has poor worst-case behavior: Klee and Minty constructed a family of linear programming problems for which the simplex method takes a number of steps exponential in the problem size.[6][9][10] In fact, for some time it was not known whether the linear programming problem was solvable in polynomial time, i.e. of complexity class P." [1]

Generally you cannot expect your solution time to scale in proportion to you problem size.

Have you tried other solvers such as CPLEX our GUROBI? They're often much faster.

> Do you now how the solver exactly works? I couldn’t find any answer.
> If you have any idea or link for me – I prefer a website in german  thank you for your help.

See also [1] or the German version ;-)

[1] https://en.wikipedia.org/wiki/Linear_programming

**Comment by Benedikt4** [comment]
> Could you provide some output details such as the solver stream which gives you the solution method and problem size (matrix)?

Thanks for your answer :)
Here are the output: 
With one demand in the system:
Problem has 210245 rows, 315364 columns (131402 with objective) and 630726 elements
There are 1 singletons with objective 52560 singletons with no objective 
Column breakdown:
192724 of type 0.0->inf, 122640 of type 0.0->up, 0 of type lo->inf, 
0 of type lo->up, 0 of type free, 0 of type fixed, 
0 of type -inf->0.0, 0 of type -inf->up, 0 of type 0.0->1.0 
Row breakdown:
132908 of type E 0.0, 1 of type E 1.0, 0 of type E -1.0, 
51049 of type E other, 0 of type G 0.0, 0 of type G 1.0, 
0 of type G other, 26280 of type L 0.0, 0 of type L 1.0, 
7 of type L other, 0 of type Range 0.0->1.0, 0 of type Range other, 
0 of type Free 
Presolve determined that the problem was infeasible with tolerance of 1e-008
Analysis indicates model infeasible or unbounded
Perturbing problem by 0.001 % of 78740.079 - largest nonzero change 0.067727149 (% 0.05618439) - largest zero change 0.067722841
0  Obj 4.4911276e+011 Primal inf 2.559535e+009 (59813)
1000  Obj 4.5101129e+011 Primal inf 2.5637516e+009 (59038)
2000  Obj 4.5405115e+011 Primal inf 2.5607941e+009 (58235)
3000  Obj 4.8794562e+011 Primal inf 2.6130336e+009 (57501)
3255  Obj 4.8920946e+011 Primal inf 2.566662e+009 (57300)
……….
128382  Obj 1.6384541e+013 Primal inf 6.0004356e+008 (5) Dual inf 2.5973983e-006 (1)
Primal infeasible - objective value 1.6384541e+013
PrimalInfeasible objective 1.638454066e+013 - 128382 iterations time 36.552

Result - Linear relaxation infeasible

Enumerated nodes:           0
Total iterations:           0
Time (CPU seconds):         38.55

With two demands in the system:
.....
155933  Obj 1.1686988e+014 Primal inf 3.7517663e+010 (20494)
Primal infeasible - objective value 1.1686988e+014
PrimalInfeasible objective 1.16869879e+014 - 155933 iterations time 1728.062

Result - Linear relaxation infeasible

Enumerated nodes:           0
Total iterations:           0
Time (CPU seconds):         1729.80


> Generally you cannot expect your solution time to scale in proportion to you problem size.

Of course, i didnt expect it in proportion, but i also didnt expect that it takes such a long time. But the simplex method should be the reason. 

> Have you tried other solvers such as CPLEX our GUROBI? They're often much faster.

How can i integrate them, i would like to compare the calculation time for my energsystem. 
And do you know more about these solvers, about the method how to solve a problem ?

**Comment by uvchik** [comment]
As I know it is also possible to use the "Interior Point" method with the cbc. It might be faster on large problems.

**Comment by Benedikt4** [comment]
> As I know it is also possible to use the "Interior Point" method with the cbc. It might be faster on large problems.

It sounds interesting. But how can I change the method ?

**Comment by simnh** [comment]
Well I am not sure if I missed something, but your solver output indicates that you are trying to solve an infeasible model. I already wondered myself at some point why cbc even starts, if it 'thinks' the problem is not feasible. So you should make sure that you problem is feasible, than it might be faster...because feasible at all...

And I think cbc does not provide interior point method.

If you work in an academic environment I suggest installing gurobi for all testing purposes because from my experiences errors/warnings are better than from the other solvers.

**Comment by Benedikt4** [comment]
I was thinking about that too. But i don´t know how to change that "infeasible problem" to an "feasible problem". i get results, but they need much time. i can´t see an "infeasible problem".

But first, how can i integrate Gurobi ?

**Comment by simnh** [comment]
If it's feasible most of the time the bus-balances are not feasible...you may either set the balance attribute of a bus to 'false', or (and this is better) add 'slack' components i.e. sinks/sources with high variable costs and not upper limit on the flow to the buses...then - if the problem is feasible - you will see at which slack component the flow occurs and this will help you be finding the 'error'...or the constraint(s) that cause the infeasibility 

http://www.gurobi.com/documentation/

You can download it for free, install it and receive a license...

**Comment by uvchik** [comment]
As it is not a developing related issue it is moved to [stackoverflow](http://stackoverflow.com/questions/43140502/solver-time-seems-to-be-to-high-for-a-small-energy-model-using-oemof-solph-wit).
