### ISSUE TITLE
Find a way for string representation of 'blocks' inside solph

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#32]
At the moment solph uses blocks for every base class to group constraints and variables etc. Blocks are 
attributes of the OptimizationModel() instance. Names of the attributes are set with the class name converted to a string. 

This is very unhandy for debugging and model analysis (e.g. lp-files) and for calling these attributes as well as they can only be called with getattr(model, str(class)).

We should find a way to have a simple, stringent and short string representation for the blocks.

**Comment by simonhilpert** [comment]
@gnn should we set the milestone to february? How is the progress for this issue?

**Comment by gnn** [comment]
Yeah, we should move this to the february milstone. Sorry.

**Comment by uvchik** [comment]
That's a pity. Still hoping that it will be fixed some day because it causes me some problems. I found a workaround by converting the tuple to a string but after the optimisation I have to convert the string back to a tuple which is possible but annoying. But if it is difficult to fix this I could implement a function that converts strings to tuples. 

@gnn : So what is you schedule?

**Comment by cswh** [comment]
and March it is ;)

**Comment by uvchik** [comment]
I think this is obsolete due to the new re-factoring.
