### ISSUE TITLE
Remove integration branches

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#343]
What about these branches, can they be removed?

 remotes/origin/integration/dlsk-sh
 remotes/origin/integration/renpassgis-znes-2050
 remotes/origin/integration/renpassgis_emob

**Comment by ckaldemeyer** [comment]
> remotes/origin/integration/dlsk-sh

Yes. I'll do it!

**Comment by ckaldemeyer** [comment]
What about

> remotes/origin/integration/renpassgis-znes-2050
> remotes/origin/integration/renpassgis_emob

 @s3pp : Do you know if these are needed?!

**Comment by uvchik** [comment]
@birgits Shall we keep the deprecated branches?

 * `origin/deprecated/dev`
 * `origin/deprecated/master`

We have the v0.0.10 label, so that it is still be possible to checkout this version, but I would not recommand any development there and therefore remove the branches. As we still have the label anyone can feel free to fork and go on with v0.0.10, if there might be reason to do so. If you just want to run your old model you can use `git checkout v0.0.10`.

Furthermore, is there any need for the `emob` branch?

 * `origin/integration/renpassgis_emob`

**Comment by s3pp** [comment]
>What about

>> remotes/origin/integration/renpassgis-znes-2050

This branch is used and still needed by Marion in the context of her PhD thesis. If possible it would be nice to keep that until after she will have submitted her work! If that's an issue I will pass that information.

>> remotes/origin/integration/renpassgis_emob

I don't know.

**Comment by uvchik** [comment]
I talked to @birgits and I will remove the following branches:

 * `origin/integration/renpassgis_emob`
 * `origin/deprecated/dev`
 * `origin/deprecated/master`

The `emob` branch is not needed any more. The `depreciated` branches point (more or less) to the same commit (568bd974e). This commit can be reached by `git checkout v0.0.10` to run old models. The branches are obsolete.

**Comment by uvchik** [comment]
One is kept all the other have been removed. Thank you for bringing this up and cleaning the repository.
