### ISSUE TITLE
[website] Replace Applications by Projects

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#35]
As a proposal I would remove the applications sections (as its anyway too difficult to maintain this stuff) and replace this a a project section instead. 

What do you think?

**Comment by busiing** [comment]
I was involved in the discussion about the project replacement. As far as I remember (correct me if I'm wrong) was there a consensus that it is definitely interesting to publish working energy models (examples). It's not just a good move to show who is/was working on stuff (projects) but also published existing models.

But in both cases without detailed information. Just short(er) description and links.

The argument was PR. For oemof and for oemof users (two-way).
1. User decision: oemof is awesome look at all this stuff and institutions - let's do oemof ourselves.
2. oemof representer: We do oemof. Look at all this stuff and institutions. Support us!

**Comment by busiing** [comment]
In addition to the change, we wanted to create a Factsheet for the applications and projects (with hints about the separation to reduce mix-ups)  with a pre-defined field, which shall be filled out.

Etherpad from developer meeting 2018:*
"template for projects includes - "Add your own project" --> link to template and example"

*https://etherpad.net/p/3u8zT3RMbd

**Comment by c-moeller** [comment]
What about using consequently the OEP factsheets for our applications and just link to them from the oemof website (without having an own applications list): https://openenergy-platform.org/factsheets/models/ ?
As far as I know we should do this anyway.

@simnh you are right that maintaining all this stuff is quite hard. I'm in the middle of setting up the project website and this already is a lot of stuff....

**Comment by c-moeller** [comment]
> In addition to the change, we wanted to create a Factsheet for the applications and projects (with hints about the separation to reduce mix-ups) with a pre-defined field, which shall be filled out.

We found out that this won't be possible with our wordpress plan. But we could present our mail address and encourage people to send us a mail.

**Comment by p-snft** [comment]
Well, doing it in an easy-to-maintain way is not possible with our current Worpress plan. Still, manual sorting is possible.

**Comment by simnh** [comment]
I just think it would be easier to show people, institutions and projects, because also applications are outdated for example renpassGIS or Hesysopt and this needs to be checked every time. While projects have finite start and end date. But I am not attached to much...Just some thoughts...

**Comment by ckaldemeyer** [comment]
> I just think it would be easier to show people, institutions and projects, because also applications are outdated for example renpassGIS or Hesysopt and this needs to be checked every time. While projects have finite start and end date. But I am not attached to much...Just some thoughts...

Do you mean running research projects or "development projects" such as TESPy?

**Comment by p-snft** [comment]
At the dev meeting, we defined it to be research projects. (Still, a TESPy-related research project might be listed.)

**Comment by ckaldemeyer** [comment]
> At the dev meeting, we defined it to be research projects. (Still, a TESPy-related research project might be listed.)

:+1: Thanks. I didn't remember but like the idea!

**Comment by c-moeller** [comment]
I created a draft of a project page. I mainly implemented the outcome from the breakout group at the developer meeting. I left out the main institutions, because it is too complicated to decide which institutions to be involved and they should also be found on the project website (-> no double structure). @oemof/oemof-website What do you think?

![oemof_projects](https://user-images.githubusercontent.com/8330132/48718534-e54b7580-ec1b-11e8-8367-01b7767db443.png)

**Comment by c-moeller** [comment]
So far I gathered only three projects. Do we have some more? What about all the Flensburg projects?

**Comment by ckaldemeyer** [comment]
> So far I gathered only three projects. Do we have some more? What about all the Flensburg projects?

We have the Stadtwerke-Project which has just finished (probably not interesting anymore) and now we (HS/Uni) are working on the following project: http://www.angus2.de/de/angus-ii

@simnh might know more about other projects at the university!

**Comment by c-moeller** [comment]
@ckaldemeyer could you prepare your project like the other projects (description max 400 chars, time period, project website, picture if you like)? This would be really nice :-)

@oemof/oemof-website if no one objects to the structure I would like to publish the page till the end of this week (or give the task to someone else since I will be not available from next week till the end of the year). But I think the first draft is already fine, so it could be published, and further projects could be added gradually.

**Comment by c-moeller** [comment]
I would also suggest to include reegis and renpassGIS from the applications page (if we delete the applications page). Somehow they are projects, too, or what do you think @uvchik @simnh

**Comment by p-snft** [comment]
Actually, the word "applications" was quite confusing for me: oemof is applied in projects, I expected what we now want to name "projects". On sites of commercial projects, the item would probably be called "references".

Long story short: The terms are quite exchangeable, so imho its sufficient to list applications/projects on one page.

**Comment by c-moeller** [comment]
> Long story short: The terms are quite exchangeable, so imho its sufficient to list applications/projects on one page.

:+1: This would be also my preferred option.

**Comment by c-moeller** [comment]
We have now a project sub page: https://oemof.org/projects/
If you want more projects to be published please follow the instructions on the top of the page. I would still be happy to see renpassGis and reegis (the former applications) on this page.... :-)

@simnh can we close this for now?

**Comment by busiing** [comment]
Update:
The oemof model tab is different from the OEP factsheet. ATM the tab shows the models very briefly and without as many technical details as on OEP. 
(I wanted to add them as example but there are too many points on the OEP factsheet.)
Since we have way fewer models the option to filter them with those details (I guess that's the point of having them in that table) is not given.

If it is still wanted that our website follows the same detail level as the OEP factsheet further discussion is necessary.

**Comment by busiing** [comment]
Since no further discussion developed this issue is considered not relevant at this point.
