### ISSUE TITLE
Implement rolling - optimization in solph  

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#35]
It makes sense to implement a rolling timehorizon for optimization problems in the solph module for two reasons:

- more realistic results
- reduction of memory usage for very large problems

**Comment by ckaldemeyer** [comment]
Maybe we should already collect what's needed for the implementation:

* Variables that have to be passed from end(runX) to start(runY)
  * Storage filling levels
  * Commodity availabilities such as biomass, coal etc.
  * Only for MILP problems: component statuses (Binary Vars)

**Comment by gplssm** [comment]
Do you already have a finalized the methodology in a theoretical way, respectively do you need input on methodology of rolling time horizon for dispatch planning? 

I ask because [Mathis](http://wupperinst.org/en/contact/details/wi/c/s/cd/1387/) implemented similar things working on the [ReStore2050 project](http://forschung-energiespeicher.info/en/wind-to-hydrogen/project-list/project-details/74/Stromversorgung_und_Speicherbedarf_im_Jahr_2050/).

**Comment by simonhilpert** [comment]
We already started on the {https://github.com/oemof/oemof_base/tree/features/solph-rolling-timehorizon] features/solph-rolling branch

**Comment by gplssm** [comment]
Fine :)

**Comment by simonhilpert** [comment]
can someone test this functionality,e.g. @ckaldemeyer ? 

I will set the milestone to february...

**Comment by ckaldemeyer** [comment]
Yes, I'll test it if I find some time between this paper slavery. Thanks!

**Comment by birgits** [comment]
@ckaldemeyer: What's the status of this issue? Should it be forwarded to the next release?

**Comment by ckaldemeyer** [comment]
@birgits : Yes, please! I just don't find time...

**Comment by ckaldemeyer** [comment]
Closed in favour of #200
