### ISSUE TITLE
Naming of CHP components

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#361]
How do we want to name the CHP-Components?

@ckaldemeyer create a `GenericCHP` and I created a `VariableFractionTransformer`.

Shall we rename the  `VariableFractionTransformer` to `LinearCHP`?

@oemof/oemof-solph Any ideas?

**Comment by simnh** [comment]
No ideas here, but vote up for renaming VariableFractionTransformer to something less cryptic :)

**Comment by uvchik** [comment]
1. `ExtractionTurbineCHP` in contrast to `GenericCHP`
 2. `CHPExtractionTurbine`
 3. `ExtractionTurbine`
 4. `LinearCHP` in contrast to `GenericCHP`

@oemof/oemof-developer-group I guess we all hate naming decision but a feedback would be helpful.

I tent to rename it to (3) or (1).

**Comment by ckaldemeyer** [comment]
> ExtractionTurbineCHP in contrast to GenericCHP
> CHPExtractionTurbine
> ExtractionTurbine
> LinearCHP in contrast to GenericCHP
> @oemof/oemof-developer-group I guess we all hate naming decision but a feedback would be helpful.
> 
> I tent to rename it to (3) or (1).

I vote to leave it `GenericCHP` as it is since it can represent back-pressure turbines, extraction turbines and motoric chps and it is well documented (Mollenhauer, E., Christidis, A., Tsatsaronis, G.: Evaluation of an energy- and exergy-based generic modeling approach of combined heat and power (CHP) plants, In: Proceedings of the 28th International Conference on Efficiency, Cost Optimization, Simulation and Environmental Impact of Energy Systems (ECOS), Pau, 2015).

I don't like `LinearCHP` since (from how I understand it) it can only be used to model extraction turbines. So maybe just `ExtractionTurbine`? ? `GenericCHP` is also linear but additionally uses integer variables. So the name `LinearCHP` could be misleading from my point of view because one might think that  `GenericCHP` is not linear or something similar wrong ;-)

**Comment by uvchik** [comment]
> I vote to leave it GenericCHP

@ckaldemeyer Maybe the title of the issue is a bit confusing but reading the text it should be clear that this is not about renaming the `GenericCHP` but about renaming the `VariableFractionTransformer`. It just would be nice if the name would be in a good relation to `GenericCHP`, so that the people understand the different ideas quickly. 

> So maybe just ExtractionTurbine? ?

Does that mean you would vote for option (3) ?

**Comment by uvchik** [comment]
Closed in favour of #375.
