### ISSUE TITLE
Add linear relation to LinearTransformers 

### ISSUE THREAD

**Issue by mloenneberga** [oemof/oemof#364]
Hi everyone, 

i would like to integrate a linear relation into a Transformer rather than using a conversion factor. It would help me to model an efficiency curve where \eta ~ (inflow_transformer-b)/a with a and b being constant factors. Since it is yet not possible to integrate this as a constraint, i would like to discuss where to place this within oemof. 

One suggestion would be to add an if-case , so that, if Transformer has no attribute conversion_factors the linear method will be used. 

What do you think?

**Comment by uvchik** [comment]
First of all every improvement is appreciated.

As you will develop a new feature you have to check out the `dev` branch. You will see that the `Transformer` class slightly changed. It is now called just `Transformer` and it has N inputs and N outputs. The new `Transformer` replaces all existing transformer classes.

If you think your approach will work for all use cases of this `Transformer` you can add your approach to the `Transformer` class. Otherwise you can add a new component in the new `custom_components` module. These components can be restricted e.g. to one input and one output.

**Comment by simnh** [comment]
I agree with @uvchik regarding the location. Maybe, best you start with a pull request and a proposal. But if no conversion factor is provided you still need to provide a and b...but a proposal would help to discuss.

**Comment by jnnr** [comment]
Is there a PR for this issue already?

**Comment by uvchik** [comment]
#377 and #424

**Comment by jnnr** [comment]
PR #424 is the more generic one and has been merged.
