### ISSUE TITLE
Question about the plot functionality of the outputlib

### ISSUE THREAD

**Issue by birgits** [oemof/oemof#367]
First of all thank you very much for the hard work on version 0.2!
When I was updating my example to the new version I saw that the plot function is not part of the outputlib any more. I was wondering if it is a final decision to not offer any plot functionalities with the new outputlib any more or if this is just temporary because nobody had the time yet to adapt it to the new version @oemof/oemof-developer-group ?

**Comment by uvchik** [comment]
I have already adapted the old plotting class. You can find it in the [`plotting module`](https://github.com/oemof/oemof/blob/features/plotting_module/oemof/outputlib/plot.py) branch. I used the `storage_investment` and the `variable_chp` example to test it. I added these examples to the [examples repository](https://github.com/oemof/examples/tree/dev/examples/oemof_0.2).

I just got the feeling that such module is not really wanted so I wandered where to put it. But of course we have to discuss this until the release.

Actually I think the outputlib is a good place for a plotting module? What do the others think?

**Comment by ckaldemeyer** [comment]
> First of all thank you very much for the hard work on version 0.2!
> When I was updating my example to the new version I saw that the plot function is not part of the outputlib any more. I was wondering if it is a final decision to not offer any plot functionalities with the new outputlib any more or if this is just temporary because nobody had the time yet to adapt it to the new version @oemof/oemof-developer-group ?

As the new result-dict delivers pandas DataFrames and Series directly -from my point of view- we do not need any plotting functionalities (at least in the central oemof package).

Plotting is now really easily possible directly with the pandas objects, [well documented](https://pandas.pydata.org/pandas-docs/stable/visualization.html) and can be adapted to every level of individual detail using basic [matplotlib commands](http://matplotlib.org/) since pandas used matplotlib in the background.

Here's a small example from the [BPT](https://github.com/oemof/examples/blob/dev/examples/oemof_0.2/generic_chp/bpt.py):

    # create result object
    results = processing.results(om)

    # store as csv
    # data = results[(bpt,)]['sequences'].to_csv('results_ccet_' + file_name)

    # plot PQ diagram from component results
    data = results[(bpt,)]['sequences']
    ax = data.plot(kind='scatter', x='Q', y='P', grid=True)
    ax.set_xlabel('Q (MW)')
    ax.set_ylabel('P (MW)')
    plt.show()

    # plot thermal bus
    data = views.node(results, 'bth')['sequences']
    ax = data.plot(kind='line', drawstyle='steps-post', grid=True)
    ax.set_xlabel('Time (h)')
    ax.set_ylabel('Q (MW)')
    plt.show()

From my point of view the old plotting functionalities have created a lot of (open) questions in the past and are already quite individual (not generic). So I strongly vote for removing them ;-)

**Comment by uvchik** [comment]
> Here's a small example from the BPT:

Thank you but it has nothing to do with the functionality the plotting class provides so I do not understand the example. The plotting class provides a composition plot with about 30 lines of code. I think it is convenient to use it instead of creating your own. I implemented just the basic function and furthermore it is possible to use the entire matplotlib functionality afterwards. The best thing is, you do not have to use it it is just an offer.

> From my point of view the old plotting functionalities have created a lot of (open) questions in the past

Can you add some examples what kind of questions there were. I did not get a lot questions.

> and are already quite individual (not generic)

What do you mean with "quite individual (not generic)"? 

> we do not need any plotting functionalities (at least in the central oemof package).

I guess you do not need it. But it has been used by some users in the past and I already adapted it to the new version. So it is out of question to keep it. The question is: **Where?** and **How?**

I still think that the outputlib is a good place next to the graph plot but I could also live with an `oemof_plot` package within the oemof organisation. 

Otherwise `rli/oemof_plot` or `rli/rli_plot` would be possible but not preferred.

**Comment by ckaldemeyer** [comment]
> Here's a small example from the BPT:
> Thank you but it has nothing to do with the functionality the plotting class provides so I do not understand the example. The plotting class provides a composition plot with about 30 lines of code. I think it is convenient to use it instead of creating your own. I implemented just the basic function and furthermore it is possible to use the entire matplotlib functionality afterwards. The best thing is, you do not have to use it it is just an offer.

Well, I guess it is just a matter of taste but I prefer a more minimalistic way here and do not think any "help" is needed in this place. But if you want to maintain it, go ahead and I am fine.

> From my point of view the old plotting functionalities have created a lot of (open) questions in the past
> Can you add some examples what kind of questions there were. I did not get a lot questions.

There were questions from @c-moeller and some during the user-meeting which I could not answer. It was about color codes, ...

> and are already quite individual (not generic)
> What do you mean with "quite individual (not generic)"?

That as soon as it comes to plotting, opinions diverge e.g. about color palettes, line styles or even plotting packages such as seaborn, etc. Thus, I do not like to include any additional plotting within oemof (my point of view) since we could leave it to the users.

> we do not need any plotting functionalities (at least in the central oemof package).
> I guess you do not need it. But it has been used by some users in the past and I already adapted it to the new version. So it is out of question to keep it. The question is: Where? and How?

From my opinion not within oemof core/solph but rather in the examples repository. As far as I know this would also be @simnh s and @s3pp s opinion.

> I still think that the outputlib is a good place next to the graph plot but I could also live with an oemof_plot package within the oemof organisation.
> 
> Otherwise rli/oemof_plot or rli/rli_plot would be possible but not preferred.

Both options are also o.k. for me with a preference to the `rli/*` variant since I am quite sure no one from ZNES would use it. But both are o.k. for me ;-)

**Comment by ckaldemeyer** [comment]
I know this has been a heavy discussion since the existence of the first outputlib but we still have different opinions on this :smile:

**Comment by uvchik** [comment]
> Both options are also o.k. for me with a preference to the rli/* variant since I am quite sure no one from ZNES would use it.

Wow, that's a statement. Let's better stop this....

**Comment by ckaldemeyer** [comment]
> Both options are also o.k. for me with a preference to the rli/* variant since I am quite sure no one from ZNES would use it.
> Wow, that's a statement. Let's better stop this....

I am sorry, this wasn't generally against using such a solution but just my opinion about the place where to keep it! It wasn't meant to offend anybody or judging your work. To me it's just about preferences and how to manage the code base.

I will re-open it and we should discuss it then!

**Comment by ckaldemeyer** [comment]
I talked to @uvchik via telephone and we decided to discuss ways for the inclusion of (optional) functionalities on the next developer meeting. So we leave this issue open as a reminder..

**Comment by birgits** [comment]
Sorry for having started such a heated discussion again but I guess we should solve this debate for good at some point anyway. I totally understand your arguments concerning the various different tastes about plots @ckaldemeyer and that none of you use it. For us at RLI this kind of plot has become very common to use but is actually not very easy to set up or at least not in a few lines. I extensively use it for debugging and understanding correlations especially between different sectors and think it could be very helpful for users as well. Maybe starting a new repository oemof_plot in the oemof organisation is a good compromise for having it close to oemof and for other users to be able to find and use it.

**Comment by birgits** [comment]
Or let's discuss it at the developer meeting ;)

**Comment by ckaldemeyer** [comment]
> Or let's discuss it at the developer meeting ;)

:+1:  :smile:

**Comment by ckaldemeyer** [comment]
> Sorry for having started such a heated discussion again but I guess we should solve this debate for good at some point anyway. I totally understand your arguments concerning the various different tastes about plots @ckaldemeyer and that none of you use it. For us at RLI this kind of plot has become very common to use but is actually not very easy to set up or at least not in a few lines. I extensively use it for debugging and understanding correlations especially between different sectors and think it could be very helpful for users as well. Maybe starting a new repository oemof_plot in the oemof organisation is a good compromise for having it close to oemof and for other users to be able to find and use it.

I think discussion about major changes/questions are always better on direct channels which are less prone to misunderstandings ;-)

**Comment by uvchik** [comment]
Plotting module was moved to [oemof-visio](https://github.com/oemof/oemof_visio).
