### ISSUE TITLE
some notes on v0.2

### ISSUE THREAD

**Issue by nesnoj** [oemof/oemof#379]
I'm an oemof newb and have been using the v0.2.0dev for a couple of days - some notes:

- `pygraphviz` and `networkx` not in setup.py . Is this wanted since the `graph_tools` are sort of additional?
- a note on the (possibly) painful installation of `pygraphviz` ([1](https://stackoverflow.com/questions/40528048/pip-install-pygraphviz-no-package-libcgraph-found), [2](https://github.com/pygraphviz/pygraphviz/issues/71#issuecomment-138999823)) of `pygraphviz` might be helpful (but maybe outside of what docs usually cover)
- rename csv_reader in examples to xlsx_reader or similar?

If you like, I can open a PR..

**Comment by uvchik** [comment]
1) Yes, by now these tools are add ons. Even though this might change because there are people who would like to implement graph analyses based on networkx so it may become more important.
2) We do have a [wiki for such things](https://github.com/oemof/oemof/wiki/Help:-Installation) but it is hardly used.
3) I am not sure how to name it because I want to catch the people who are searching for the csv-Reader. In the end it should be renamed.

**Comment by nesnoj** [comment]
Thx
