### ISSUE TITLE
Remove "nominal_input/output_capacity_ratio" for GenericStorage

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#381]
I am using the `GenericStorage` object (without investment) to model some components and just stumbled upon a weird behaviour:

It always uses a `nominal_input/output_capacity_ratio` to set the upper bounds of the inflows and outflows in relation to the maximum available capacity. If no values are passed, the `nominal_input/output_capacity_ratio` is set to `0.2` and generally sets the respective upper bounds of the flow.

Let's say I want some storage with a capacity of 700 MWh at 10 MW maximum charging/discharging power with NonConvex in-/outflows within a load range from 50 to 100 %.

This can be realized via:

    STES = solph.components.GenericStorage(
        label='STES',
        inputs={HNW: solph.Flow(
            min=0.5, max=1, nonconvex=solph.NonConvex())},
        outputs={HNW: solph.Flow(
            min=0.5, max=1, nonconvex=solph.NonConvex())},
        nominal_capacity=700,
        nominal_input_capacity_ratio=5/700, nominal_output_capacity_ratio=5/700
    )

But if I now define a regular nominal capacity for an in- or outflow it is ignored because of the ratio. To me the API is not clear here and I would find it much clearer if the nominal capacity is defined within the flows and the ratio removed completely.

I know it is needed for the investment variant but in my opinion misleading and unnecessary for the regular one.. So I would remove it!

@oemof/oemof-developer-group : What do you think?

**Comment by uvchik** [comment]
This is related to #311.

People modelling batteries are used to define the `c-rate` instead of a maximum input power even though most of the time it is not called `nominal_input_capacity_ratio` 😏 

> I know it is needed for the investment variant but in my opinion misleading and unnecessary for the regular one.. So I would remove it!

As you noticed it is needed for the investment storage so removing the attribute is not a very constructive proposal ❗️ 

At the moment we find something like this:
```python
if self.nominal_capacity is not None:
    flow.nominal_value = self.nominal_output_capacity_ratio * self.nominal_capacity
```

We could change the default value for nominal_out/input_capacity_ratio to 'None'. Then we will have the opportunity to make both ways possible.

```python
if flow.nominal_value is not None and self.nominal_output_capacity_ratio is not None:
    raise AttributeError ("Duplicate definition of.....")
elif self.nominal_output_capacity_ratio is not None and self.nominal_capacity is not None:
    flow.nominal_value = self.nominal_output_capacity_ratio * self.nominal_capacity
```

In the past both ways were possible but some developers insisted that we should make it more explicit by having just one possible way. We made the mistake to not raise an error when a given nominal value is overwritten.

I think it is a good way to allow both ways and raise an error if contradictory attributes were set instead of preferring one attribute over the other.

**Comment by ckaldemeyer** [comment]
> This is related to #311.
> 
> People modelling batteries are used to define the c-rate instead of a maximum input power even though most of the time it is not called nominal_input_capacity_ratio

Yes, I would say some battery people think this way but not all. And the storage is not only for batteries but should be a "simple" storage for different purposes. At least that's how I think about it ;-)

> As you noticed it is needed for the investment storage so removing the attribute is not a very constructive proposal.
> 
> At the moment we find something like this:
> 
> if self.nominal_capacity is not None:
>     flow.nominal_value = self.nominal_output_capacity_ratio * self.nominal_capacity
> We could change the default value for nominal_out/input_capacity_ratio to 'None'. Then we will have the opportunity to make both ways possible.
> 
> if flow.nominal_value is not None and self.nominal_output_capacity_ratio is not None:
>     raise AttributeError ("Duplicate definition of.....")
> elif self.nominal_output_capacity_ratio is not None and self.nominal_capacity is not None:
>     flow.nominal_value = self.nominal_output_capacity_ratio * self.nominal_capacity

I would just like to make the standard API not overriding the explicit definition of flow capacities. It can still be dealt with in the background as you mentioned with the idea of `None` values.

> In the past both ways were possible but some developers insisted that we should make it more explicit by having just one possible way. We made the mistake to not raise an error when a given nominal value is overwritten.

Who was this? Not me because I think this is much more implicit ;-)

> I think it is a good way to allow both ways and raise an error if contradictory attributes were set instead of preferring one attribute over the other.

I agree!

**Comment by uvchik** [comment]
The more general a component is the more difficult it is to design and name it to everybody's satisfaction.

As you agree with my proposal we can make a PR. Let us coordinate ourself next week so that we will not have two PRs 😏.

Even though my proposal does not change the backward compatibility I would like to make it part of the v0.2 release.

**Comment by ckaldemeyer** [comment]
> The more general a component is the more difficult it is to design and name it to everybody's satisfaction.
> 
> As you agree with my proposal we can make a PR. Let us coordinate ourself next week so that we will not have two PRs .
> 
> Even though my proposal does not change the backward compatibility I would like to make it part of the v0.2 release.

:+1:

**Comment by uvchik** [comment]
Done with PR #388.
