### ISSUE TITLE
Renaming the code folder of oemof_base to avoid errors

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#45]
@oemof/oemof-main : Shall we just rename the code folder to oemof_base?

The python convention is to name the code folder as the package name. @gnn said that it should also work with different named folders but right now it causes errors (see #44).

As long as nobody knows how to avoid these errors I vote for renaming the code folder to oemof_base.

I label it urgent because at the moment the example does not work if you install oemof using
`pip3 install oemof_base`.

**Comment by ckaldemeyer** [comment]
+1 for renaming

**Comment by cswh** [comment]
+1 for renaming and having the general convention to use oemof_base and not oemof-base as a rule of thumb.

**Comment by ckaldemeyer** [comment]
@simonhilpert @gnn @caro-rli @birgits @wolfbunke ?

**Comment by caro-rli** [comment]
If it avoids errors I'm for renaming.

**Comment by wolfbunke** [comment]
+1 me too

**Comment by uvchik** [comment]
@caro-rli wrote : 
> If it avoids errors I'm for renaming.

I don't know for sure and and I do not know how to test. So I suggest to rename it with the next release and hope that it will work afterwards. According to #44 it seems to me that the different names could cause the error. I found that in python repositories the name of the code folder and the name of the repository should be the same.

**Comment by uvchik** [comment]
I created a branch `change_name_code_dir` to apply the changes.

1. I changed the folder name from `oemof` to `oemof_base`
2. I changed the definition in the setup.py file
2. I changed the import in the example files
3. I changed all imports within the package to relative imports and removed the absolute imports
4. I tested everything successfully

We should merge this directly to the release branch. I will help you if there are any problems.

**Comment by uvchik** [comment]
I talked to @gnn and he might have a better idea.

**Comment by uvchik** [comment]
If we change the structure we may also include the version number according to [pep-0396](https://www.python.org/dev/peps/pep-0396/).

You don't have to read it. It just says, that you should be possible to get the version number by typing the following.

```python
import oemof
print(oemof.__version__)
```

@gnn : Do you know how to do it?

**Comment by gnn** [comment]
:-1: from me for moving to `oemof_base` for pypi-package as well as import package.
In my opinion this is a move into the wrong direction. What happens if we factor out e.g. solph? then solph moves to the package `oemof_solph` and suddenly everybody has to change his/her imports from `oemof.solph` to `oemof_solph`.
I also checked out the `change_name_code_dir` branch and after installing from a source distribution, `import oemof_base` failed for me so I think this change does not really fix #44.
See the issue for what I think is the real culprit and the corresponding fix.

In my opinion it would be better to rename the (pypi)-packages to `oemof` and `oemof.pg` (well, `oemof.db` really, but that's a different discussion and not really important) respectively (which entails changing the `oemof_pg` directory structure by adding a `pg` subdirectory to the `oemof` root.) That way moving (import)-packages into separate (pypi)-packages changes nearly nothing. This way of doing things is also [documented][https://pythonhosted.org/setuptools/setuptools.html#namespace-packages] and seems to be the preferred way of splitting packages into namespace packages.
The only problem is that I don't know whether this works with namespaces actually containing something, i.e. not just working as an empty "umbrella" namespace.
But I could test this with local source distributions.

Concerning the version, check features/PEP-0396ification.

**Comment by uvchik** [comment]
Sounds comprehensible :+1: 

So I would rename the oemof_pg package (`oemof.db` is okay for me). That means that the package is named `oemof.db` and within the package is a folder named `db` or `oemof.pd`. Or would you do the restructuring?

So the new structure of oemof will be as follows:

oemof
* core
* outputlib
* solph
* tools

That means the name `base` will no longer exist? And if we want to outsource `solph` the new package name would be `oemof.solph` and no import will change. Did I get it right?

**Comment by uvchik** [comment]
Will you merge `features/PEP-0396ification` ?

**Comment by ckaldemeyer** [comment]
> So the new structure of oemof will be as follows:

> oemof
> * core
> * outputlib
> * solph
> * tools

To me Günnis proposal looks cleaner than the current approach. :+1:

**Comment by gnn** [comment]
Features `features/PEP-0396ification` merged.
I also renamed the PyPI packages to `oemof` and `oemof.db` respectively, via the entries in their `name` arguments in their `setup.py` files. They should be uploaded to the correct packages now.
I also restructured the directory layout way you already anticipated. For the package formerly known as `oemof_base` I didn't have to do anything while `oemof.db` now looks like this:

```
./root-folder
  |- setup.py
  |- [..]
  |- oemof/
     |- __init__.py
     |- db/
        |- __init__.py
        |- coastdat.py
        |- [usw.]
```

So there's not too much to change in existing code. Details are in the commit message to 74b45d6ca53252551d8e8e77b2892ba429a9ed0b.
The changes are on the oemof_base/features/namespace-package and oemof_pg/features/namespace-package branches respectively. I didn't merge them yet, cause I thought you guys might want to have a look at them first.
@simonhilpert When you do the release tomorrow, you can also [rename the repositories](https://help.github.com/articles/renaming-a-repository/) so everything is nice and clean and consistent.

**Comment by simonhilpert** [comment]
if everything works now, we can close this issue.

**Comment by uvchik** [comment]
It did not work for me but I opened a new issue ( #78 ). Thank you for releasing the new structure. Looks cleaner.
