### ISSUE TITLE
Error: Cannot run example "simple_dispatch"

### ISSUE THREAD

**Issue by henhuy** [oemof/oemof#464]
We just tried to simply run:
_oemof_examples/examples/oemof_2.0/simple_dispatch/simple_dispatch.py_ 
within a fresh environment and oemof installed via 
`pip install oemof`
But the following error occured:
`"Index '(<oemof.solph.network.Bus object at 0x7f1681a639a8>, 0)' is not valid for indexed component 'Bus.balance'"`
Any hints?

**Comment by uvchik** [comment]
Which commit?

**Comment by uvchik** [comment]
Sorry, if you use `pip install` you have v0.2.0 installed.

This is an Pyomo issue. Use `pip install pyomo==5.3`.

**Comment by uvchik** [comment]
This issuee will be fixed with the release of v0.2.1 which is delayed due to illness. I will be released in a few days. Afterwards you can update pyomo again using `pip install pyomo --upgrade`.

**Comment by henhuy** [comment]
Works again! thank you!

**Comment by uvchik** [comment]
I reopen this as a reminder.

I suggest to limit the version of each required package in the setup.py to the most actual (working) version on every oemof release. The reason is that otherwise `pip install oemof` will always install the most actual version of each package at the moment of the installation. This behaviour may lead to errors (as seen above) if the the API of one required package changed since the last oemof release.

@henhuy and @ckaldemeyer already agree on that.

**Comment by uvchik** [comment]
Closed in favour of #465.
