### ISSUE TITLE
Making the result object a class

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#470]
I know we already thought about this. But I think a class with method instead of functions for the processing and particularly views as wells as writing results to csv for example could really help...should not be too much of an effort...

What do you think?

**Comment by ckaldemeyer** [comment]
> I know we already thought about this. But I think a class with method instead of functions for the processing and particularly views as wells as writing results to csv for example could really help...should not be too much of an effort...
> 
> What do you think?

I could go with it as long as we do not blow it up with specific plotting code!

**Comment by ckaldemeyer** [comment]
But I won't spend time on it..

**Comment by simnh** [comment]
No, no plotting, just methods for user-friendly result processing :-) ..

**Comment by ckaldemeyer** [comment]
> No, no plotting, just methods for user-friendly result processing :-) ..

:+1:

**Comment by uvchik** [comment]
As there are always different ways to a good solution I am fine with the procedural approach as well as an object oriented approach. The new proposal should be at least as good as the existing functionality :smile: 

@henhuy thought in the same direction maybe you could talk to him to share your ideas.

@ckaldemeyer In December we moved the plotting module to an extra repository (oemof-visio) and in January we removed the plotting functions from the graph module. Since v0.2.0 the matplotlib is no longer a requirement of oemof as decided on the developer meeting. I think a refactoring from a procedural approach to an object oriented approach has nothing to do with this decision.

**Comment by ckaldemeyer** [comment]
> As there are always different ways to a good solution I am fine with the procedural approach as well as an object oriented approach. The new proposal should be at least as good as the existing functionality smile
> 
> @henhuy thought in the same direction maybe you could talk to him to share your ideas.
> 
> @ckaldemeyer In December we moved the plotting module to an extra repository (oemof-visio) and in January we removed the plotting functions from the graph module. Since v0.2.0 the matplotlib is no longer a requirement of oemof as decided on the developer meeting. I think a refactoring from a procedural approach to an object oriented approach has nothing to do with this decision.

:+1:

**Comment by henhuy** [comment]
I really appreciate this!
In my private branch I'm already doing so.
For example - my first adaption:
My app calculates multiple results and therefore calls the `node`-function for several nodes multiple times - to avoid this, my `Results`-object stores already made node results and only returns them, instead of calling the function again. 
To finish: I would definitely participate in creating an oemof results object!

**Comment by henhuy** [comment]
I came to the conclusion, that I'm fine with the current solution. Before, I struggled with the `results` and `param_results` dicts to generate some outputs/calculations - but I added the `analyzer`-module, which makes those things very easy (see PR #482).
Having this, I'm not dependent on a results object for now...

**Comment by uvchik** [comment]
@simnh Do you still want to bring that forward? Otherwise you could just close this issue to avoid confusions.

**Comment by birgits** [comment]
I was assigned to manage this issue at the dev meeting. As I understand @henhuy added an analyzer module in #482 which is still waiting for a review and will, once merged, make a Results class unnecessary for him. @simnh what's your opinion on that? Is the analyzer module sufficient or would you still like to provide a Results class? And in case of a yes on question number two, would you help implementing the Results class @henhuy?

**Comment by simnh** [comment]
Currently I am fine with the result as they are as we are postprocessing them in oemof tabular anyway. I did not see the functionatilties of the analyzer so far. But it will probably make sense to look at that one first before starting the next result project ;-)

**Comment by birgits** [comment]
@simnh would you like to keep this issue as a reminder or can we close it?

**Comment by simnh** [comment]
We can close it :-)
