### ISSUE TITLE
Add timedepent upper bounds for optimization variables in solph

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#55]
At the moment upper bounds can only be set as scalars. The out_max, in_max etc. attribute should be
able to take lists as well to add different upper bounds for the optimization time horizon. 

This is something that should go along with new class names and different attribute naming and attribute 
types (do not like the lists for out_max etc very much...) 
@gnn @ckaldemeyer

**Comment by ckaldemeyer** [comment]
:+1:

**Comment by uvchik** [comment]
Maybe not lists but numpy.arrays or pandas.series. I need this feature right now. I will have a look what I can do.

**Comment by simonhilpert** [comment]
I think we should stick to pandas. The problem here is that we pass out_max as lists for example 
for chp out_max = [30, 40] . But if we use pandas.Series, maybe we can check, if the entry inside the list is of type pandas.Series and than handle it.

**Comment by simonhilpert** [comment]
the code to be adapted is located: oemof.solph.variables.set_bounds()
and maybe inside the baseclasses

**Comment by uvchik** [comment]
One problem is that some other values are connected to `out_max` such as `opex_fix`. So maybe we should add `upper bound` which are use instead of out_max if they are set. But out_max is still used to define the maximum output. Another idea is to use the maximum value of the series `out_max.max()` to calculated `opex_fix`.

What do you think?

**Comment by simonhilpert** [comment]
I think out_max.max() would be better for now, in the long term we
should find a better structure for all attributes. We just have to make
sure, that if it's not a pandas.Series() the right value has to be
taken. Again for chp it should be the out_max[0] and not the maximum of
out_max as the maximum might refer to the maximum thermal output but
fixed costs generally refer to the installed electrical capacity.



Am 19.01.2016 um 15:12 schrieb ukrien:
> One problem is that some other values are connected to `out_max` such as `opex_fix`. So maybe we should add `upper bound` which are use instead of out_max if they are set. But out_max is still used to define the maximum output. Another idea is to use the maximum value of the series `out_max.max()` to calculated `opex_fix`.
> 
> What do you think? 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/oemof/oemof_base/issues/55#issuecomment-172864778
> 

-- 
ZNES

Simon Hilpert
(M.Eng. Systemtechnik)

Wissenschaftlicher Mitarbeiter
Fachbereich Energie- und Biotechnologie
Fachhochschule Flensburg
Gebäude H, Raum H217
Kanzleistraße 91-93
D- 24943 Flensburg

T: +49 (0)461 805 1562
F: +49 (0)461 805 1300

www.znes-flensburg.de
www.fh-flensburg.de
simon.hilpert@fh-flensburg.de

**Comment by uvchik** [comment]
Pull request #65 added a time depended upper bound which can be used instead of out_max for the upper bound of the out variable. But out_max is still used as the capacity and it is in charge of the user keep it consistent.

For storages next to the upper bound for the output (ub_out) and the maximal output (out_max) we have the C-rate for the output (c_rate_out). As I understand it out_max will be calculated using cap_max and the C-rate if it is not set. But in the documentation it is not clear that cap_max and the C-rate are obligate and out_max optional. Is it meant like this?

@oemof/oemof-main 
Do we all agree that the C-rate and the capacity are the obligate values and other values will be calculated from them if not given? This is more or less how it is now. Or shall it also be possible to set the capacity and the maximum output and calculated the C-rate from them?

In my opinion the code will be cleaner and it will be easier for users if we define obligate parameters and optional parameters and make clear how the optional parameters are calculated if not set. Even though you might have to define C-rate for thermal storages which is barley used.

As it is possible to have a time depended upper bound it should be possible to have a time depended C-rate. Do you prefer a new variable for this as we did it for out_max/ub_out or shall I make it possible to set the C-rate as an integer and a list.

**Comment by ckaldemeyer** [comment]
> Do we all agree that the C-rate and the capacity are the obligate values and other values will be calculated from them if not given? This is more or less how it is now.
Would be o.k. for me.
>Or shall it also be possible to set the capacity and the maximum output and calculated the C-rate from them?
But I find this option more intuitive.

I guess we can just decide it and the user has to adapt. In my opinion we should only provide degrees of freedom where they might be needed. If one way would be sufficient for all thinkable cases, we should provide that way and no others.

**Comment by uvchik** [comment]
>>Or shall it also be possible to set the capacity and the maximum output and calculated the C-rate from them?

>But I find this option more intuitive.

Me, too. All the other components are defined by `out_max`. But at the moment the C-rate is obligate. @simonhilpert , @caro-rli would you mind changing this? So that the C-rate is calculated by the capacity and `out_max`. 

But what happens if `out_max` and `ub_out` the upper bound for the output are defined. Which one do we use to calculated the C-rate? I would say `ub_out`. 

So we could make the C-rate time depended and calculate it whether from `out_max` or from `ub_out` if `ub_out` is set.

**Comment by caro-rli** [comment]
>@simonhilpert , @caro-rli would you mind changing this? So that the C-rate is calculated by the capacity and out_max. 

I don't understand how a C-rate can be calculated if you have an investment model? You don't know neither out_max nor the installed capacity, only the maximum ratio as the C-rate is known depending on the storage type. Or do I understand something wrong here?

>As it is possible to have a time depended upper bound it should be possible to have a time depended C-rate

In which cases do you need a time-dependend C-rate?

**Comment by uvchik** [comment]
>I don't understand how a C-rate can be calculated if you have an investment model? You don't know neither out_max nor the installed capacity, only the maximum ratio as the C-rate is known depending on the storage type. Or do I understand something wrong here?

You are right. If there is no capacity at the beginning it is impossible to calculate the C-rate. I just want to avoid that all ways are possible to avoid errors.

> In which cases do you need a time-dependend C-rate?

Domestic thermal storages.

**Comment by cswh** [comment]
what is the progresse here?

**Comment by birgits** [comment]
Is anyone still working on this or can we close it?

**Comment by uvchik** [comment]
It is still pending.

**Comment by ckaldemeyer** [comment]
> I don't understand how a C-rate can be calculated if you have an investment model? You don't know neither out_max nor the installed capacity, only the maximum ratio as the C-rate is known depending on the storage type. Or do I understand something wrong here?

>> You are right. If there is no capacity at the beginning it is impossible to calculate the C-rate. I just want to avoid that all ways are possible to avoid errors.

The c-rate is only used in `linear_constraints.py` in the function `add_storage_charge_discharge_limits`, right?

I am just interested: why is it important to set the upper (in-/outflow) bounds according to the c-rate?

My personal view: if we find a smart way to get rid of the c-rate, it would make things easier as it's one more definition one has to look up, think of and maintain in the code and solph logic.

> In which cases do you need a time-dependend C-rate?

>> Domestic thermal storages.

I think time-dependend c-rates (or two, separately for the storage in- and output) are really confusing and way more confusing than time-depending upper bounds ;-)

**Comment by caro-rli** [comment]
> I am just interested: why is it important to set the upper (in-/outflow) bounds according to the c-rate?

Same here.. If I don't know storage capacity or power (because they are part of my results) I cannot set any upper bounds beforehand.

Am I the only one who uses investment models? Or do I basically misunderstand something here? :confused:

**Comment by ckaldemeyer** [comment]
>> I am just interested: why is it important to set the upper (in-/outflow) bounds according to the c-rate?

> Same here.. If I don't know storage capacity or power (because they are part of my results) I cannot set any upper bounds beforehand.

What speaks against 'inf'?

> Am I the only one who uses investment models? Or do I basically misunderstand something here? :confused:

I guess so, yes. Maybe you should join the solph team to maintain the constraints ;-)

**Comment by caro-rli** [comment]
> What speaks against 'inf'?

Because I want to limit the storage power of course, but relatively.. related to the (unknown) storage capacity. So exactly what the C-Rate is doing :smile:

> Maybe you should join the solph team to maintain the constraints ;-)

I should :smile:

**Comment by ckaldemeyer** [comment]
>> What speaks against 'inf'?

> Because I want to limit the storage power of course, but relatively.. related to the (unknown) storage capacity. So exactly what the C-Rate is doing :smile:

But normally the storage power would be set (cost) optimal as low as possible anyway. The only reason I see is that it keeps capacity and power in a fixed ratio. If that's intended, o.k. but it also implies that the search space for optimal solutions is pre-defined smaller and power and capacity are not scaled independently.

>> Maybe you should join the solph team to maintain the constraints ;-)

> I should :smile:

Go for it ;)

**Comment by caro-rli** [comment]
> that it keeps capacity and power in a fixed ratio

But battery components, for example, do have a fixed ratio, once they are built as a unit (except Redox-Flow-Batteries).

And having a non-investment-model you have a fixed ratio, too, by setting the maximum output and the capacity.

**Comment by caro-rli** [comment]
> Go for it ;)

Oh, I'm in the solph team already. At least github says so :-)

**Comment by uvchik** [comment]
>My personal view: if we find a smart way to get rid of the c-rate, it would make things easier as it's one more definition one has to look up, think of and maintain in the code and solph logic.
I think time-dependend c-rates (or two, separately for the storage in- and output) are really confusing and way more confusing than time-depending upper bounds ;-)

In my opinion the most important thing is that we have one parameter for one value.
if can ensure both modes (investment or dispatch optimisation) only by using the C-rate we should use the C-rate. Than we can explain that straight and clear in the documentation and everybody will understand a time-dependent C-rate.
