### ISSUE TITLE
Improve handling of kwargs

### ISSUE THREAD

**Issue by p-snft** [oemof/oemof#560]
Update: There seem to be four degrees of possible kwarg handling:

1. Use wild card **kwargs for all key word arguments. This is currently done, e.g. in [Flow](https://github.com/oemof/oemof/blob/12a30e28f19373033c01fb9297a7de0a36568f91/oemof/solph/blocks.py#L82). Currently, this is the most common way in oemof.

2. Define known kwargs but set empty defaults. Technically, this is the same API as in 1. but it improves readability and comfort. This way was suggested [later in this ticket](https://github.com/oemof/oemof/issues/560#issuecomment-463573255). It also reduces the likeliness of typos.

3. Enforce values for obligatory quantities. This would also improve readability, and would also solve copy and paste errors, typos, etc. It would require programmers to make explicit when obligatory parameters should be left uninitialized (e.g. `Sink(inputs={})`). It is already implemented in [ExtractionTurbineCHP](https://github.com/oemof/oemof/blob/12a30e28f19373033c01fb9297a7de0a36568f91/oemof/solph/components.py#L1070) but quite uncommon in oemof.

4. Disallow faulty kwargs (like `outputs` for a `Sink`, or those including typos). This option would either cost flexibility, require some "expert mode" where strict enforcement is turned off, or need explicit checks. (Option 4 is what I originally proposed here.)

**Original text:**
I would suggest to raise errors if unknown kwargs are passed to functions. I believe this would make it greatly easier to debug code using oemof and improve the usability.

**Comment by uvchik** [comment]
Could you provide an example? 

Sometimes it is wanted to give the user the option to pass own arguments (e.g. emissions to a Flow object).

But we could add a warning for such cases which is suppressed by default but can be activated for debugging.

**Comment by henhuy** [comment]
Personally, I think we should put more stuff out of kwargs into named parameters.
But I also use them to provide additional parameters for flows. Unfortunately, this does not work for Node objects. This would be cool too!

**Comment by p-snft** [comment]
Consider copy&paste errors where a `Source` has `inputs` instead of `outputs`. The resulting model will probably still be computed, but with different results. In fact, even typos (e.g. `imputs`) may result in a system with a valid result, just with disconnected nodes.

**Comment by uvchik** [comment]
> Personally, I think we should put more stuff out of kwargs into named parameters.

1. I agree that mandatory parameters shouldn't be hidden in kwargs. This would also solve some of @p-snft 's problems. If a Sink does not have an `input` parameter an error is raised even if there is an `iMput` or an `output` parameter instead.

2. We could also think of forbidden attributes. A Source for example is not allowed to have an `input` parameter and a Sink is not allowed to have an `output` parameter.

Anything else?

@oemof/oemof-developer-group What do you think?

**Comment by fwitte** [comment]
I usually check, if the specified keywords are available for that object. In TESPy e. g. take a component c1, which has a parameter P (power) and a second component c2 with parameter Q (heat). You can specify values with c1.set_attr() and c2.set_attr() respectively. set_attr accepts kwargs but checks for available parameters, thus c1.set_attr(Q=1e5) throws an exception.
```
 var = available keys
for key in kwargs:
    if key in var:
        update component information
    else:
        Error
```

**Comment by p-snft** [comment]
I addressed this issue in a new branch. Could you provide me feedback on the style before I proceed?

**Comment by gnn** [comment]
Sorry for the late reply. @uvchik poked me about this and now that I see the whole conversation, I see that there is more to this, than I initially thought.
The first thing is about using differing function signatures in Python inheritance hierarchy.

> I would suggest to raise errors if unknown kwargs are passed to functions. I believe this would make it greatly easier to debug code using oemof and improve the usability.

Unfortunately this isn't possible. Due to Python having multiple inheritance, when you call `super()`, you don't know exactly which superclass you're getting. The order in which `super()` traverses the inheritance hierarchy changes, depending how somebody chooses to subclass. That means a function might get a keyword argument intended for a function which is located behind it in the method resolution order, so it can't raise an error, just because it doesn't recognize the argument.
Generally speaking, due to the fact that the order in which the hierarchy is traversed is dynamically computed, you cannot rely on a method on `super()` having a specific signature and you're safer just relying on `(*args, **kwargs)` (or really just `**kwargs`) and choosing very carefully when and how to validate your arguments (for example you could throw an error if the `Sink` gets `outputs` because this just violates the definition of a `Sink`).
The changes proposed on the branch mentioned above do not really trigger the problem above though, because regardless of the order in which constructors are called, missing `inputs` will always be a problem, or at least a weird anomaly, for a `Sink`.
UNLESS we're thinking about supporting assigning whole dictionaries to the `inputs` property, which brings me to the next point.
 
> Personally, I think we should put more stuff out of kwargs into named parameters.

Now this I'm opposed to, because it rules out assignment after construction. At least for parameters that directly map to attributes.
Somebody might want to write a class which doesn't use explicit `inputs`, but rather constructs everything using `super()`, then dynamically construct the `inputs` based on whatever the object at hand looks like after construction. You can technically do this, by using `node.inputs[key] = value` after construction and by forcing an `inputs` argument into the `Sink.__init__` call, we're forcing anybody who wants to do this to supply a bogus `inputs` argument. I remember that use case coming up when creating energy system objects in bulk by de-serializing from some storage format like in the CSV or the datapackage reader. When doing something like this, objects aren't created simultaneously, so not having to care about the fact whether an input or an output already exists is a huge blessing when writing code like this. On top of that, just having the `inputs` argument be present doesn't mean that it's non-empty.
These are the reasons why I'm not in favour of the changes proposed on the branch above.

All's not lost in terms of validation, though. @uvchik and me came to the conclusion, that having some kind of sanity check that gets run before trying to optimize the energy system would be beneficial. Such a sanity check could incorporate checking whether every sink/source has at least one input/output respectively, or it could even check whether the graph is weakly connected, in case one wants to hit it with a bigger hammer. Or even any other check one would come up with.

Also, the style on the new branch is top notch. A small, atomic commit with a nice heading and a nice message. :+1: 
If I would want to be really, really picky, I'd vote for writing "inputs/outputs" and "Sink/Source" instead of using commas but that's after trying hard really hard to find something. ;)

> But I also use them to provide additional parameters for flows. Unfortunately, this does not work for Node objects. This would be cool too!

I guess you're referring to the fact that `Node`s can't have any attributes beyond what is specified in the `__slots__` attribute? Can you elaborate? Maybe there's an easy way to fix this.

**Comment by p-snft** [comment]
> > I would suggest to raise errors if unknown kwargs are passed to functions. I believe this would make it greatly easier to debug code using oemof and improve the usability.
> 
> Unfortunately this isn't possible. Due to Python having multiple inheritance, when you call `super()`, you don't know exactly which superclass you're getting. The order in which `super()` traverses the inheritance hierarchy changes, depending how somebody chooses to subclass. That means a function might get a keyword argument intended for a function which is located behind it in the method resolution order, so it can't raise an error, just because it doesn't recognize the argument.
> The changes proposed on the branch mentioned above do not really trigger the problem above though, because regardless of the order in which constructors are called, missing `inputs` will always be a problem, or at least a weird anomaly, for a `Sink`.
> UNLESS we're thinking about supporting assigning whole dictionaries to the `inputs` property, which brings me to the next point. 

What I proposed initially was already discarded. Instead, the new idea was to enforce obligatory parameters. The initial suggestion seems to be really misleading by now, as you noticed that the branch does not implement the initial idea. The implementation of the initial suggestion would almost certainly have lead to fixed signatures with explicitly defined key word arguments. Even custom **kwargs would have been possible, for example when you explicitly allow them using an additional "expert mode" keyword like `custom=True`. However, this would have been a bigger step, so 

According your point concerning super(): I [made a change](https://github.com/oemof/oemof/commit/4877fe517db32035416ecece2a97fbc1e141b5e3) to overcome this problem. (There should have been no problem with using super() in this case, though. But I hopefully still got the point.) Also, the same style was already used e.g. in [solph/blocks.py](https://github.com/oemof/oemof/blob/12a30e28f19373033c01fb9297a7de0a36568f91/oemof/solph/blocks.py#L82).


> > Personally, I think we should put more stuff out of kwargs into named parameters.
> 
> Now this I'm opposed to, because it rules out assignment after construction. At least for parameters that directly map to attributes.
> Somebody might want to write a class which doesn't use explicit `inputs`, but rather constructs everything using `super()`, then dynamically construct the `inputs` based on whatever the object at hand looks like after construction.

Here, again, it is flexibility versus taking users by the hand. (I would not call one of them _user friendly design_, as one is more friendly to experienced users and one is to novice users.) At this point, I would opt for defining required arguments. When I want a sink without inputs, I should make it explicit `Sink(inputs={})`. You might call this a bogus argument but it would help those who need help while at the same time improving readability of the code. (The reader directly sees that you do not want to define `inputs` right now.)

> All's not lost in terms of validation, though. @uvchik and me came to the conclusion that having some kind of sanity check that gets run before trying to optimize the energy system would be beneficial. Such a sanity check could incorporate checking whether every sink/source has at least one input/output respectively, or it could even check whether the graph is weakly connected, in case one wants to hit it with a bigger hammer. Or even any other check one would come up with.

This would be another option. However, if it spreads definition and sanity check to two locations it would be harder to maintain. So alternatively, one could require classes to have a `sanity_check()` that would then be called by a global sanity check that iterates over all objects providing such a function. Still, I would be in favour of requiring arguments on construction, as this seems to be the more intuitive way.

> Also, the style on the new branch is top notch. A small, atomic commit with a nice heading and a nice message. +1
> If I would want to be really, really picky, I'd vote for writing "inputs/outputs" and "Sink/Source" instead of using commas but that's after trying really hard to find something. ;)

Thanks for your feedback, I really wanted to make things clean and clear. (PS: I first used a slash but replaced it as it looked like a path separator.)

**Comment by henhuy** [comment]
In my point of view, changing `kwargs` into named parameters would not lead to any changes in flexibility, but would highly increase readability! At the moment, most components with `kwargs` initialize all parameters anyway - so changing it to named parameters with default values would lead to same effect. Maybe an example is best to show what I mean...

Have a look at current `solph.network.Flow` implementation for example:
```
class Flow:
    def __init__(self, **kwargs):
        # TODO: Check if we can inherit from pyomo.core.base.var _VarData
        # then we need to create the var object with
        # pyomo.core.base.IndexedVarWithDomain before any Flow is created.
        # E.g. create the variable in the energy system and populate with
        # information afterwards when creating objects.

        scalars = ['nominal_value', 'summed_max', 'summed_min',
                   'investment', 'nonconvex', 'integer', 'fixed']
        sequences = ['actual_value', 'variable_costs', 'min', 'max']
        dictionaries = ['positive_gradient', 'negative_gradient']
        defaults = {'fixed': False, 'min': 0, 'max': 1, 'variable_costs': 0,
                    'positive_gradient': {'ub': None, 'costs': 0},
                    'negative_gradient': {'ub': None, 'costs': 0},
                    }

        for attribute in set(scalars + sequences + dictionaries + list(kwargs)):
            value = kwargs.get(attribute, defaults.get(attribute))
            if attribute in dictionaries:
                setattr(self, attribute, {'ub': sequence(value['ub']),
                                          'costs': value['costs']})
            elif 'fixed_costs' in attribute:
                raise AttributeError(
                         "The `fixed_costs` attribute has been removed"
                         " with v0.2!")
            else:
                setattr(self, attribute,
                        sequence(value) if attribute in sequences else value)

        # Checking for impossible attribute combinations
        if self.fixed and self.actual_value[0] is None:
            raise ValueError("Cannot fix flow value to None.\n Please "
                             "set the actual_value attribute of the flow")
        if self.investment and self.nominal_value is not None:
            raise ValueError("Using the investment object the nominal_value"
                             " has to be set to None.")
        if self.investment and self.nonconvex:
            raise ValueError("Investment flows cannot be combined with " +
                             "nonconvex flows!")
```
When looking at the code above, it takes several minutes for me to check what is really happening.
But this could be easily refactored to:
```
class Flow:
    def __init__(
            self, nominal_value=None, summed_max=None, summed_min=None, 
            investment=None, nonconvex=None, integer=None, fixed=False, 
            actual_value=sequence(None), variable_costs=sequence(0), 
            min=sequence(0), max=sequence(1), 
            positive_gradient={'ub': sequence(None), 'costs': 0},
            negative_gradient={'ub': sequence(None), 'costs': 0},
            **kwargs
    ):
        self.nominal_value = nominal_value
        self.summed_max = summed_max
        self.summed_min = summed_min
        self.investment = investment
        self.nonconvex = nonconvex
        self.integer = integer
        self.fixed = fixed
        self.actual_value = actual_value
        self.variable_costs = variable_costs
        self.min = min
        self.max = max
        self.positive_gradient = positive_gradient
        self.negative_gradient = negative_gradient
        
        for k, v in kwargs.items():
            setattr(self, k, v)

        # Checking for impossible attribute combinations
        if self.fixed and self.actual_value[0] is None:
            raise ValueError("Cannot fix flow value to None.\n Please "
                             "set the actual_value attribute of the flow")
        if self.investment and self.nominal_value is not None:
            raise ValueError(
                "Using the investment object the nominal_value"
                " has to be set to None.")
        if self.investment and self.nonconvex:
            raise ValueError("Investment flows cannot be combined with " +
                             "nonconvex flows!")
```
This would have the exact same impact, but one would see exactly what happens if I don't pass specific arguments! Additionally, for people like me, using an IDE, at component initialization it would show me all optional parameters and their default values - nice ;)

**Comment by p-snft** [comment]
I have structured the options (see initial post) and would suggest to start implementing option 2 which does not change the API but improves readability and comfort. As it does not break the API, it would not hurt to be completed after the release ov v0.3.0. Also, these changes would also be needed  for options 3 and 4.

Whether to switch to option 3 or 4 should be discussed at the user meeting. (Switching to 3 would mean to delete default `=None` arguments which would be simple but still require more than a fix release.)

**Comment by henhuy** [comment]
I vote for option 2!
Option 3 (API change!) would be okay for me in some cases - but I feel no special need for it.
and I don't like options 1 & 4

**Comment by jnnr** [comment]
I vote for option 2  because of its better readability. And as you said, option 3 might be relevant in some cases, especially for more special components. Thx for this discussion!

**Comment by uvchik** [comment]
I like option 2. I think it gives us a lot of opportunities. But adding a check will change the API, because a former optional attribute is now mandatory. At the moment it possible to initiate the node and add an `input` or `output` later. I think it is very rare, but I remember that we once had a case where the objects were initiated in that way.

However, I think it is a good idea and as @p-snft mentioned it will help to avoid errors in the model.

To keep the behaviour in some way we could add an optional `check_attr` parameter which is True by default. If you really want to skip the check you can just pass `check_attr=False`, otherwise you have to do nothing.

```python
def __init__(**kwargs):
    if kwargs.get('check_attr', True) is True:
        # check attributes
        ....
```

This may take @gnn doubts into account, but I am not sure.

**Comment by p-snft** [comment]
A possible (optional) check for set attributes could be implemented like:

```python
_NO_DEFAULT = object()

class ExampleClass
    def __init__(self, mandatory=_NO_DEFAULT, optional=None, check_attr=False):
        if check_attr and _NO_DEFAULT in locals().values():
            raise TypeError
        ...
```

As, `_NO_DEFAULT` is a default value for the mandatory argument, the build in check for mandatory arguments would be turned off. The (optional) check is performed by testing for this dummy value which should typically be replaced. Instead of introducing a local `check_attr`, it would also be possible to have a global setting to turn argument checks on or off. Also, it would be possible to introduce different levels (none, warning, strict).

**Comment by p-snft** [comment]
Another option (for v0.4) would be, to strictly disallow unknown kwargs. Instead, one would pass a custom "expert_kwargs" dict. This way, errors due to API changes (see e.g. #601) cannot happen.

**Comment by uvchik** [comment]
It is very important to find a solution here as some classes already do have optional or mandatory parameters. We should be consistent in either way.

* [GenericStorage](https://github.com/oemof/oemof/blob/dev/oemof/solph/components.py#L127) -> optional parameters (`max_storage_level`, `min_storage_level`)
* [ExtractionTurbineCHP](https://github.com/oemof/oemof/blob/dev/oemof/solph/components.py#L1143) -> mandatory parameter (`conversion_factor_full_condensation`)

**Comment by uvchik** [comment]
> Another variant of 4. would be, to strictly disallow unknown kwargs. Instead, one would pass a custom "expert_kwargs" dict. This way, errors due to API changes (see e.g. #601) cannot happen. (This would be something for a v0.4 release.)

I like this idea. People will be aware that they add something not typical and that it will not have any effect unless they do something else like adding an additional constraint etc..

We do not have to wait until v0.4. We could already start with warnings.

We should remove all mandatory and optional parameters to be consistent (as mentioned above).

**Comment by uvchik** [comment]
A compromise found on the last user meeting was to introduce a `SuspiciousUsageWarning`. This warning will be raised if components are used in an untypical but possible way -> #663 

@p-snft Anything left from this issue or is this okay by now.

**Comment by p-snft** [comment]
The check should solve the known problems. Thank you!
