### ISSUE TITLE
[meeting] 2020 oemof Spring Meeting (virtual!) (dev&user)

### ISSUE THREAD

**Issue by joroeder** [oemof/oemof#59]
Dear oemof community, oemof users, and friends of oemof

due to the current circumstances, the oemof spring meeting will take place virtually (and not in Bremen as planned before).

As usual, you will find the detailed information about the meeting in the wiki:
[https://github.com/oemof/oemof/wiki/Meeting-May-2020-%28online%29 ](https://github.com/oemof/oemof/wiki/Meeting-May-2020-%28online%29)

Please, write your name in the wiki in the Participants section or in this issue, if you are going to participate.

The agenda will be filled the next weeks and can be discussed in this issue.

We look forward meeting you 💻 🎧 🎤 😊

**Comment by fwitte** [comment]
Is it possible to post there for non members of the oemof/organisation repo? Last time it did not work, I think.

**Comment by Tino6989** [comment]
Test

**Comment by joroeder** [comment]
> 
> 
> Is it possible to post there for non members of the oemof/organisation repo? Last time it did not work, I think.

Thanks for the hint! We just tested it, it seems to work, even non members can leave a commet here.

**Comment by fwitte** [comment]
In this issue yes, but on the wiki?

**Comment by joroeder** [comment]
Therefore, the people can simply post here in the issue something like "I want to join, can you please put me on the list" and me or somebody else will put her/him on the list in the wiki.

**Comment by c-moeller** [comment]
Can we add a list where people can add their topic suggestions which will later be transferred to the agenda?

**Comment by joroeder** [comment]
I added a subsection in the wiki, where suggestions for topics can go (Please feel free to adapt):
[https://github.com/oemof/organisation/wiki/Meeting-May-2020#list-of-topics](https://github.com/oemof/organisation/wiki/Meeting-May-2020#list-of-topics)

For all, who cannot edit the wiki, same as for the list of participants: you are very welcome to post topics in this issue you like to have. Don't be shy, especially for the user part, we are very happy about input.

As soon as there are a few suggestions, we will sort them and make a first suggestions for a agenda.

**Comment by fwitte** [comment]
Due to the ongoing COVID-19 crisis we should consider postponing or canceling the meeting in may and maybe moving to an online conference instead. What do you as hosts think, @joroeder and @uvchik?
Have a nice evening

**Comment by joroeder** [comment]
Sorry for the late response! We decided to hold the fisrt virtual oemof conference! The date stays the same. More details coming soon ...

**Comment by joroeder** [comment]
The wiki is already updated, please see: [https://github.com/oemof/organisation/wiki/Meeting-May-2020-%28online%29](https://github.com/oemof/organisation/wiki/Meeting-May-2020-%28online%29) - Feedback for improvement is welcome!

Everyone is invited to contribute sessions! This time, it would be helpful to finish the schedule earlier because the sessions can no longer be postponed spontaneously during the meeting.

Since the Uni Bremen people are organising the next physical meeting in autumn/winter, everybody is encouraged to support the organisation of this virtual meeting 😊

**Comment by c-moeller** [comment]
If you like to contribute a session (which can be tutorials/webinars with a user focus or virtual meetings with a developer focus), please write it into the wiki (https://github.com/oemof/organisation/wiki/Meeting-May-2020-%28online%29) or in this issue (if you don't have write access).

**Deadline is April 30th 2020!**

**Comment by jokochems** [comment]
Hi,
I'd like to participate but I don't have writing access to the wiki yet.
I could provide the following contributions:
- User section: power market modeling in oemof
- Dev section: progress in demand response modeling

If you provide me with writing access to the wiki, I could add a description there. Elsewhise, I'll return here for details.

Thanks a lot

**Comment by joroeder** [comment]
hey, sounds nice! @uvchik @jnnr could somebody add  @jokochems  as member? :) As soon as you are a member, you can edit the wiki I think. And in the second step, you could be part of a group, if you want. See https://github.com/oemof/oemof/issues/26 for more info.

**Comment by uvchik** [comment]
Done!

**Comment by Fernando3161** [comment]
Hi! I would like to participate. I am interested in possible implementation other components in the tool. (Fernando Penaherrera V. UOL/OFFIS)

**Comment by B-Uhle** [comment]
Hi, 
like last year i would like to participate at the user meeting again. 
Thanks, Björn

**Comment by joroeder** [comment]
@Fernando3161 @B-Uhle I added you to the list 😉

**Comment by fwitte** [comment]
Hi everyone,
if there is anyone interested in TESPy specific development (new components/equations/...) please let me know. I will then schedule a time slot for this. Otherwise my contributions (regarding TESPy) will only have some kind of "organizational" nature (related to #58).
Cheers!

**Comment by nesnoj** [comment]
Hey folks,

first of all, thanks for organizing the meeting! :)

@c-moeller and I are trying to figure out what web conferencing tool suits our needs for the user sessions. If I'm not mistaken, the dev sessions are gonna use jitsi?

I prefer jitsi too as we've gained some good experience in the last months (and it's OS). But we've only tested with a maximum of ~20 participants and according to [1] a maximum of 35 p. should not be exceeded. Furthermore, a major drawback of jitsi is the performance if participants use a browser other than Chrome/Chromium - I've been told that just one Firefox user is enough to slow down the stream for all (!) users.. so I'm a little worried that it's all gonna run smoothly with jitsi.

I guess as it's way easier to simply login than to travel to a meeting in real life, we should be able to handle more than 50 attendees, right? This also seems to rule out jitsi. What do you think? Does anyone of you has tried out jitsi on a larger scale?

There're other alternative tools which are free of charge [1] (only WebEx seems to meet the requirements) but I haven't tried those. 

Fortunately, there's a fallback option: We could use our RLI Zoom account which has been approved to work well with a large number of users.
Personally, I despise Zoom for several reasons (won't open up this can of worms here). But if there's no other option, we can use it.

Another important aspect is to protect the meetings against bombings. Although it's quite unlikely, I guess there're some crawlers around which auto-collect zoom links. Therefore I'd recommend to set a password. This would also help not to exceed a certain amount of attendees, if required.
What do you think? And how could we share it privately? The latest openmod sessions make use of a private forum post in order to share it. We could do it the same way or set up a simple form where users have to register and we send the credentials via email.
(or we publish a hash of the password and the user must look it up manually in a rainbow table which at least would exclude the dumb crawlers ;)

I'd be happy if you could share your thoughts and experiences..

[1] https://www.heise.de/ct/artikel/Kostenlose-Videokonferenz-Programme-im-Funktionsueberblick-4704912.html

**Comment by c-moeller** [comment]
Today @uvchik and I had the idea to make the tutorial sessions only with a few participants and share it on youtube or any other platform. Then there will be no participants restrictions. People could ask their questions via comments. What do you think?

**Comment by nesnoj** [comment]
That's sound! Jitsi is able to stream it to YT..
So the channel would be restricted to e.g. the people who listed their name in the wiki (currently 13).

Does the oemof group have a google/yt account?

**Comment by smartie2076** [comment]
I have something else that could be on the agenda - something like a session for project pitches:
About an 1 or 1.5 hr block open for people to present their current projects, using screenshare an a short presentation of 3 slides only. That way new and old users would be updated on current projects, would have the ability to network. Combined with an etherpad, people might even self-organize and have spontaneous breakout groups on their project topics after the pitches. 

If the mail with the programme were to be sent out till the beginning of next week, I think everyone interested would have enough time to prepare a 3-slide presentation.

**Comment by gplssm** [comment]
It's actually recommended to use a YT stream for Jitsi session with more than 35/50 participants. [Here](https://geeksocket.in/posts/live-stream-meetup-event/) someone reports on his experience.

**Comment by fwitte** [comment]
> It's actually recommended to use a YT stream for Jitsi session with more than 35/50 participants. [Here](https://geeksocket.in/posts/live-stream-meetup-event/) someone reports on his experience.

Hi,
I have been doing this for my lectures in this semester, it works quite nice.

There are three minor issues I have experienced:

- Sometimes the streaming is stopped by jit.si but usually resolved within less than 5 minutes.
- You can not change the app you are sharing for the other users to see on youtube. It seems as if when you change e.g. between presentation and a console or a script in an editor, the people on jit.si will see the change, but on youtube the sharing of the screen will just stop. In order to fix this, you need to reconnect to jit.si and restart screen sharing.
- Another way would be sharing your whole screen. Downside here is, that you cannot select one of your screens individually but it will then always be all of your screens.

Cheers
Francesco

**Comment by joroeder** [comment]
> 
> 
> I have something else that could be on the agenda - something like a session for project pitches:
> About an 1 or 1.5 hr block open for people to present their current projects, using screenshare an a short presentation of 3 slides only. That way new and old users would be updated on current projects, would have the ability to network. Combined with an etherpad, people might even self-organize and have spontaneous breakout groups on their project topics after the pitches.
> 
> If the mail with the programme were to be sent out till the beginning of next week, I think everyone interested would have enough time to prepare a 3-slide presentation.

I think that is a good suggestions. I added this session to the wiki, and opened and issue #72 where everybody can write his/her topic. (maybe it is easier than using this issue).

@smartie2076 could you take care of that session?

**Comment by joroeder** [comment]
I made a suggestion for the agenda. Please see #73

**Comment by nesnoj** [comment]
Following the experiences and recommendations from above, we will check out Jitsi+YT stream.

In @gplssm's link
> It's actually recommended to use a YT stream for Jitsi session with more than 35/50 participants. [Here](https://geeksocket.in/posts/live-stream-meetup-event/) someone reports on his experience.

it says
_"Make sure you have enabled live streaming by following the instructions given here. This takes 24 hours to get enabled, so make sure you do the setup at least 1 day before the event."_. So it's a good idea to set this up soon.

As this meeting/webinar probably won't be the last by the oemof community, do you think it's a good idea to set up a general oemof YT/Google account for the stream @uvchik @joroeder?

**Comment by nesnoj** [comment]
If someone would like Zoom for backup, please let me know until tomorrow **(May 6th)** and I'll keep the room blocked for you session.
@jnnr @jokochems @c-moeller @Ludee @busiing @birgits @uvchik

**Comment by busiing** [comment]
When can session chair test the chosen presentation tool? Otherwise, I can not tell if a backup is necessary.

**Comment by nesnoj** [comment]
@uvchik proposed DFN conf and we had a short test today with his account. As it worked well (incl. stream), I think we can rely upon this solution. Do you (or someone else) need a test or are you familiar with DFN conf?

@uvchik Could you please take care of this?

**Comment by jokochems** [comment]
@nesnoj: I'd like to have Zoom as a backup option. (I have an account from my university which I could use as well for this purpose.)

Furthermore, I don't think using DFN conf is such a good idea. Though in general it is quite stable, due to increased access and very limited server capacity, I experienced quite some trouble with this tool a while ago. This may not be the case anymore since it has been a couple of weeks ago.

@nesnoj and others: Please keep providing helpful info and instructions for tools to use, esp. the preferred Jitsi + YT combination.

**Comment by busiing** [comment]
@nesnoj Yes, I would like to test it very much. Otherwise, I am sure it won't be a smooth presentation ;-)

**Comment by pz-max** [comment]
Hi everyone, 
would like to participate in some parts of the user/dev meeting.
I am just about to choose a model for my PhD to (~improving storage designs by changing materials, layout etc). Hope to get some impressions of what's going on here. Thanks.

**Comment by nesnoj** [comment]
> Hi everyone,
> would like to participate in some parts of the user/dev meeting.

Great, I added you to the [list of participants](https://github.com/oemof/oemof/wiki/Meeting-May-2020-(online)).

**Comment by uvchik** [comment]
We have tested DFN yesterday and it worked fine. I will test it again at different times.

Everybody is free to test different variants or backup solutions. Jitsi and YT could be a backup, but I do not have time to test it.

**Comment by birgits** [comment]
Will we use DFN for dev sessions as well?

**Comment by uvchik** [comment]
> Will we use DFN for dev sessions as well?

Yes, if there are no objections.

**Comment by uvchik** [comment]
Please edit the Program here:

https://ethercalc.org/b2zg1e72npzv

**Comment by fra-mezzera** [comment]
Hello everyone,
I am a university collaborator that works at Politecnico di Milano and I have used oemof framework for my Master thesis.
I would like to participate at some user meeting in order to improve my knowlegde of the topic. I do not have the rights to modify the list of participants, could You add me to the event?
Thanks in advance

**Comment by nesnoj** [comment]
> could You add me to the event?

:+1: Done

**Comment by tscherwath** [comment]
Hello everyone,

could you add me to the list of participants: Tim Scherwath from BBHC 

best
Tim

**Comment by Bitte1Bit** [comment]
Hello everyone,

I would also like to participate in the spring meeting and I would be glad if you add me to the list of participants: Martin Dotzauer DBFZ Deutsches Biomasseforschungszentrum gemeinnützige GmbH

best regards
Martin

**Comment by henhuy** [comment]
Hello,
could you add me to participants?
Thanks!
Best regards
Hendrik

**Comment by fra-mezzera** [comment]
Hello,
I saw that DFN will be used for sharing the event and a link is available on the Program sheet. I don't know the platform, so will the right to participate be reserved only to members added to the list or will the event be open-access like a Youtube streaming? If the former, will it be necessary to add some credentials?
Thanks!

**Comment by mheiker** [comment]
Hello,
could you add me as participant?
Thanks in advance!
Mathias

**Comment by uvchik** [comment]
The stream is always available and the link can be found here: 

https://ethercalc.org/b2zg1e72npzv

In the stream questions can be asked via the chat. If you want to be part of the session and be able to talk you have to send an e-mail with the sessions you want to take part to the following address:

oemof_spring_meeting_2020@posteo.eu

On Tuesday night you will get an e-mail with all login details. The 22 participants, on [this list](
https://github.com/oemof/oemof/wiki/Meeting-May-2020-%28online%29#participants) will have priority. The limit for each session is 22.

**Comment by smartie2076** [comment]
I will take over the pitch session. However, it would be important that all speakers can actually speak (ie. get a registration link for DFN). @uvchik will they all be able to share their screen with their presentations? Otherwise, they would need to either be able to post their pdf in the chat for me to open or share it beforehand.

As they are only 5 people planning to have a pitch, I will probably follow up the presentation with a short Q&A round.

**Comment by makki111** [comment]
Hi everyone!
I would like to register to the event 

Thanks!
Samuel

**Comment by joroeder** [comment]
> 
> 
> I will take over the pitch session.

Thank you!

> However, it would be important that all speakers can actually speak (ie. get a registration link for DFN). @uvchik will they all be able to share their screen with their presentations? Otherwise, they would need to either be able to post their pdf in the chat for me to open or share it beforehand.

Maybe, we can meet 15 min before the session and everybody can test?

> 
> As they are only 5 people planning to have a pitch, I will probably follow up the presentation with a short Q&A round.

👍

**Comment by joroeder** [comment]
We still need somebody to take care of the welcome and closing session? Any volunteers? 😉
If nobody else wants to do that, I could moderate the welcome session. Who wants to chairs the feedback and closing session?

**Comment by makki111** [comment]
Thank you guys for registering me!
To update my registration account (participant n.25), my surname is Macchi, and I am research fellow from Politecnico di milano

Thanks!
Samuel Macchi

**Comment by joroeder** [comment]
hey everybody,

now, there is an etherpad for documentation:

[https://etherpad.wikimedia.org/p/oemof-dev-user-2020](https://etherpad.wikimedia.org/p/oemof-dev-user-2020)

The most important notes/outcomes of each session should be noted there. These can be open questions, things further to discuss, groups of intereset, and so on.

**Comment by c-moeller** [comment]
Is there actually interest in the session "aggregation of decentralization solar power systems"? I did not prepare a presentation or so... I just wanted to shortly explain our approach, which we already discussed in this issue https://github.com/oemof/oemof-solph/issues/647 because maybe this could be relevant for other projects. In the project oemof_heat we unfortunately do not have any more time to deal with this topic.

**Comment by JulianBarinton** [comment]
Hi, dear oemof community,

In the upcoming days I am starting to work at RLI on a tool based on oemof and offgridders for "Enabling Site-Tailored and Integrated Water, Energy, and Food Systems through the Development of an Open-Source Configuration Tool." Martha told me that you have a virtual oemof meeting these days. Unfortunately, I was busy with other meetings and WG-Suche here in Berlin, but I would be pleased to join today.

I am looking forward to meeting you virtually and in person.

Kind regards,
Julian

**Comment by busiing** [comment]
Dear presenters of the oemof meeting,
please link your presentations to the [ethercalc](https://ethercalc.org/b2zg1e72npzv) (timetable) or send it to me via email (see ethercalc).

**Comment by uvchik** [comment]
- next meeting: 2.-4.12.2020
 - web-conference 9.9.2020 corona check, if virtual or real meeting
 - if real meeting is possible, Bremen will be host
 - otherwise virtual meeting, who can organize?

**Comment by joroeder** [comment]
oh, I just saw that we wanted to do a web-conference last week about how to organize the next oemof meeting ;-) I think this is clear ;-)

The big question is, who will organise the next virtual meeting?

**Comment by p-snft** [comment]
I opened a ticket do the next event - we should proceed there.
