### ISSUE TITLE
New component: Stratified Thermal Storage

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof#621]
We want to represent stratified thermal storages more in detail. Therefore we want to implement the following component. Any feedback or experiences are warm welcome!

A simplified 2-zone-model of a stratified thermal energy storage can be formulated like this:

- We assume a cylindrical storage with of diameter d and height h, with two temperature regions that are perfectly separated. 
- The temperatures are assumed to be constant and correspond to the feedin/return temperature of the heating system. 
- Heat conductivity of the storage has to be passed as well as a timeseries for outside temperatures for the calculation of heat losses. 
- There is no distinction between outside temperature and ground temperature.
- Material properties are constant.

In the case of investment, the diameter d is given and the height can be adapted to adapt the nominal capacity of the storage. With this assumption, all relations stay linear.

**Comment by jnnr** [comment]
![heat_storage](https://user-images.githubusercontent.com/32454596/60095750-95073980-974f-11e9-855b-4ad2ce4152d7.png)

**Comment by jnnr** [comment]
![2DG_OEM_ESP_01_1-0](https://user-images.githubusercontent.com/32454596/60095782-afd9ae00-974f-11e9-889c-28e7861ce6a3.jpg)

**Comment by jnnr** [comment]
The loss term looks a bit different than in the GenericStorage. In case of investment, there are a two more equations. This suggests that a new component would be necessary.

**Comment by simnh** [comment]
Nice idea, definitely a new component. Maybe someday we eventually also get a battery model, which is more complex than the generic storage! 

Contentwise: I am not a thermal engineer ;-), but sounds good anyway. Go for it!

**Comment by joroeder** [comment]
Hey, nice, very interesting!

in the end, this component has an additional constant loss, which does not depend on the state of charge. Did I get it right? The term -U*A*(Q_t-1/Q_N)*delta(T_HC) could be modeled with the existing loss_rate, but a constant loss -U*A**delta(T_C0) independent of the state of charge does not exists at the moment (like for the transformer and flows ( #618 )).

For the investment, the diameter needs to fixed, and all the other stuff results from it with a given Q_N - which is a variable... am I right? Because an optimal diameter - high relation would results in a NLP..

How about adapting the existing general storage by a constant loss, and doing a face class out it with all the precalculations you described? I am happy to help :)

**Comment by p-snft** [comment]
I support @joroeder's idea to allow a constant loss in the GenericStorage and to add a facade.

**Comment by jnnr** [comment]
Thanks for your feedback. I like the idea of separating the approach into a facade and a constant loss factor. As @p-snft remarks, this could be useful in other contexts as well. I will open a new PR.

Just for clarification - in the presented approach, the stored thermal energy is defined by the difference between inlet and outlet rather than relative to the ambient temperature.

**Comment by jnnr** [comment]
Two PRs, one in oemof, one in oemof-thermal, implement the proposed feature. I close the issue
