### ISSUE TITLE
Typo errors inputs, outputs

### ISSUE THREAD

**Issue by joroeder** [oemof/oemof#670]
If somebody does a typo in ```inputs``` or ```outputs``` when defining a component, there is no error or warning. I think @uvchik mentioned this error at the last dev meeting. Maybe this error happens more often, especialley to new users and might have fatal consequences. Eventually the total calculation is running without error and a sink or a source or whatever might be not connected to the energy system.

How could this be implemented? Do we need an error message in every component, which defines ```inputs``` and ```outputs```?

**Comment by uvchik** [comment]
see PR #663 

We invented a "SuspiciousUsageWarning". We cannot raise an error by default because it is possible and allowed to initialise a `Sink` without `outputs` or a `Source` without `inputs` and so on if you know what you are doing. With an internal Warning everybody is free to get nothing, a warning or an error. So people who know what they are doing are not annoyed by several warnings.

I personally prefer warnings over errors in that case because you see all suspicious code at once. If an error is raised the script will stop after the first occurrence.

```python
# switch on warnings
warnings.filterwarnings("always", category=SuspiciousUsageWarning)

# raise an error
warnings.filterwarnings("error", category=SuspiciousUsageWarning)

# switch off
warnings.filterwarnings("ignore", category=SuspiciousUsageWarning)
```

**Comment by uvchik** [comment]
In PR #663 we started with Sinks without outputs and Sources without inputs and Transformer with less than one input or less than one output. But we can use it for everything that might be wrong in most use cases. Feel free to add ideas to the PR.

**Comment by joroeder** [comment]
Okay, thanks for the hint. Actually, I was not sure whether that is a separate topic ;)

**Comment by uvchik** [comment]
You are right there wasn't an issue, just the PR and the PR does not explain the basic idea. So we may connect this issue with the PR and leave it open until the PR is finished.

**Comment by joroeder** [comment]
I think we can close this Issue now, since #663 has been merged. right?
