### ISSUE TITLE
Documentation of some Flow parameters is not coherent

### ISSUE THREAD

**Issue by jakob-wo** [oemof/oemof#687]
The three parameters `max`, `min`, and `actual_value` of the `oemof.solph.network.Flow` differ in their documentation, although they have one essential property in common: they are all _normed_ (not absolute) values.

Just the `max` documentation makes that very clear:

> max (numeric (iterable or scalar)) – **Normed** maximum value of the flow. 

The term _nominal_ that is used in the `min` description makes it sound like the absolute minimum of the `nominal_value` - we sould try to avoid confusions here!

> min (numeric (iterable or scalar)) – **Nominal** minimum value of the flow

> actual_value (numeric (iterable or scalar)) – **Specific** value for the flow variable.

In #547 we agreed on renaming `actual_value` `fix` - that will highlight the similarity of the three parameters. 
To emphasis the similarity in the documentation text as well, I propose to use the term _Normed_ in all three descriptions.

@oemof/documentation What do you think?

**Comment by jakob-wo** [comment]
Ok, I will open a PR soon to update the docu using _Normed_ in all three descriptions.

**Comment by joroeder** [comment]
> Ok, I will open a PR soon to update the docu using Normed in all three descriptions.

@jakob-wo 
Which three descripitions do you mean? The 3 attributes (min, max, actual), or in three classes, where they occur (Flow, InvestmentFlow, ... some more?) ?

In #636 - which I hope to merge soon - I already updated that for the InvestmentFlow, we should use similiar descriptions in both classes (*Flow*, *InvestmentFlow*) ...

And, if not done so far, I would be really happy to get some more feedback #597  😊 
If you are updating the *Flow* docstring anyway, maybe directly to the new tempalte? 😉

**Comment by jakob-wo** [comment]
I was talking about the 3 attribute descriptions in the docstring (or is it called API?) of oemof.solph.**network**.Flow.

#597 seems to be about solph.**block** - their we don't have max, min, actual_value as far as I am aware of.
I am a bit confused but I think the new template does not work for solph.network, right?

**Comment by joroeder** [comment]
> #597 seems to be about solph.**block** - their we don't have max, min, actual_value as far as I am aware of.

We do, in the formulas and in the table of symbols. When we want to have all docstrings in such a nice appearance like the *GenericCHP*, with symbols instead of cryptic formulas (what we decided on, but not implemented for all blocks yet), there will be a table with the parameters including an explanation in each **block** docstring as well. and for the flow, there will be *min*, *max*, .. in the list of symbols table. That's why this topic is related, and a change of explanations also affects the block class.

Furthermore, I made a suggestions, which also touches the docstring of the parameter classes (to put the symbols there as well) . This is not decided yet. - you can have a look at on what I mean here: [https://oemof.readthedocs.io/en/features-add_nonconvexinvestmentflow/api/oemof.solph.html#oemof.solph.network.Flow](https://oemof.readthedocs.io/en/features-add_nonconvexinvestmentflow/api/oemof.solph.html#oemof.solph.network.Flow)

> I am a bit confused but I think the new template does not work for solph.network, right?

I fully understand that there is confusion after a while 😉
However, I hope that we get this topic done soon. It is an again and again poping up topic  (we are discussing for over an year now I think), which slows downs developments due to unclearness ... and having readable API documentation is a nice thing as well 😊

**Comment by joroeder** [comment]
So, to sum it up, if it is just the 3 attribute descriptions,  we can directly change it in the features branch *add_nonconvexinvestmentflow* (where all the other docstrings changes are included) and then, we do not need to solve merge conflichts - what do you think?

**Comment by joroeder** [comment]
What do you think about:

*min*: "Normed minimum value of the flow."
*max*: "Normed maximum value of the flow."
*actual/fix*: " Normed fixed value for the flow variable."

And *summed_max* and *summed_min* are also specific/normed. Would you use "normed" for these as well, or do you suggest to use "specific", since the values or not between 0 and 1?

**Comment by jakob-wo** [comment]
@joroeder Thank you! Your explanation and the readthedocs helps a lot!

> What do you think about:
> min: "Normed minimum value of the flow."
> max: "Normed maximum value of the flow."
> actual/fix: " Normed fixed value for the flow variable."

Yes, that is exactly what I am proposing! 👍 


> And summed_max and summed_min are also specific/normed

I am pretty sure they are absolute values and **not** normed! (That should be changed in PR #636)

> we can directly change it in the features branch add_nonconvexinvestmentflow

Absolutly 👍

**Comment by joroeder** [comment]
I changed the descriptions for the flow attributes in #636 :
[https://github.com/oemof/oemof/pull/636/commits/5aef59636ada15a2266c326d448ad77f01464639](https://github.com/oemof/oemof/pull/636/commits/5aef59636ada15a2266c326d448ad77f01464639)

The branch of #636 is available on readthedocs: [https://oemof.readthedocs.io/en/features-add_nonconvexinvestmentflow/api/oemof.solph.html#oemof.solph.network.Flow](https://oemof.readthedocs.io/en/features-add_nonconvexinvestmentflow/api/oemof.solph.html#oemof.solph.network.Flow)

Regarding *summed_min* and *summend_max*: These values are multiplied by the *nominal_capacity* or the invested capacity (+ existing capacity), respectively. So, they are not normed (if you think of values between 0 and 1), but they are specific values.
If you use a time resolution of 1 hour, *summed_min*/*summed_max* define limits for the total energy of a flow in equivalent of full-load-hours.

For *summed_min* and *summend_max*, I think calling it "specific" makes sense. Now, I changed it in the parameter symbol table of the flow.block as well:
[https://github.com/oemof/oemof/pull/636/commits/fa7f93af79873fa96ff70cab421f8fe3471fec6d](https://github.com/oemof/oemof/pull/636/commits/fa7f93af79873fa96ff70cab421f8fe3471fec6d)

So, when #636 is merged, we can close this issue?

**Comment by jakob-wo** [comment]
> Regarding summed_min and summend_max: These values are multiplied by the nominal_capacity

I actually really thought they were absolute values - I was just wrong! Sorry!

> So, when #636 is merged, we can close this issue?

Yes!
