### ISSUE TITLE
Broken apidocs of tools.economics.annuity

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof#688]
The api reference of tools.economics annuity is broken. Some text about DSM appears, which is strange.

https://oemof.readthedocs.io/en/features-add_nonconvexinvestmentflow/api/oemof.tools.html#oemof.tools.economics.annuity

 It might have to do with the missing indent of the math sections.

**Comment by nesnoj** [comment]
Thanks for bringing this up, I also stumbled across this really [weird](https://xkcd.com/1501/) bug lately.
For some reason it shows the expression from [this line](https://github.com/oemof/oemof/blob/f0034343700f2b4dde8eedc41520bd3c7c76e883/oemof/solph/custom.py#L890) written by @nailend.

Unfortunately I cannot test locally whether this is due to missing indentation (although I cannot imagine this is related) as currently I haven't set up sphinx. If you do, could you please give it a try?
