### ISSUE TITLE
Periodical web conferences

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#72]
Simon, Clemens and me just had a discussion during lunch and think that it would make sense to reinstall the web conference since there are a lot of changes at the moment and this keeps our points of views closer. 

The next "regular" date would be next Tuesday 15 pm.

What do you think?

**Comment by uvchik** [comment]
February 2nd? Fine for me. :+1:

**Comment by ckaldemeyer** [comment]
Yes! :+1:

**Comment by uvchik** [comment]
My topics so far:

* Tests
  * Test the tests
  * Examples still part of the tests? (Structure of the examples)
  * Result tests (optional)
  * Plausibility tests (outputlib)
  * obligate tests before merging?

**Comment by cswh** [comment]
Unfortunately today I have another appointment at 3 pm. But from now on, I will keep the Tuesday afternoon free again for the webkos. Additionally gnn is in holidays this week...

**Comment by uvchik** [comment]
**Outputlib**

@s3pp reported the state of the outputlib. The DataFrame class and the Plotting class will be separated and the creation of the DataFrame is becoming faster. These enhancements will be merged soon.

@ckaldemeyer and @s3pp remarked that a plotting library is not necessary because everybody will create his/her own plot anyway. @uvchik replied that he finds it quite useful to have a library of standardized plots. After the new class structure is merged  @uvchik will make a proposal to seek a mutually acceptable compromise.

**Testing**
@uvchik said that it becomes more important that everything still works after a merge, so that we should define merging rules. In his opinion test and examples are important instrument to ensure the function of the code. This topic wasn't discussed because there were only three participants.
