### ISSUE TITLE
demandlib calls (helpers.call_demandlib())

### ISSUE THREAD

**Issue by gplssm** [oemof/oemof#77]
The example for the demanlib `example_demandlib.py` uses the helper function `call_demandlib()` to call the demandlib. This helper function basically creates a suitable dataframe and checks the kwargs for appropriate input.
Is it planned to get rid of this helper function and include its functionality natively into the demandlib?

**Comment by caro-rli** [comment]
This is a good question. Originally this helper function comes from the energy_regions class, which we don't have anymore. It then was a method of the energy_regions class, which called the demandlib and in return set a demand attribute of your specific region. Guess this is now obsolete since we have a demand object. I can check how to avoid the helper function but cannot manage this before the end of the week.

**Comment by gplssm** [comment]
Thanks! Relax and stay in that position! :sunglasses:

**Comment by cswh** [comment]
what is the progress here?

**Comment by caro-rli** [comment]
Fixed with df49926ee6fdb1f9e98fa63f0ec757f01f483e40
