### ISSUE TITLE
What is the storage variable type "other" in the results dataframe?

### ISSUE THREAD

**Issue by caro-rli** [oemof/oemof#80]
I've always interpreted this as the storage soc, so maximum value would be the installed storage capacity (in investment models), but this seems not to be true. According to issue https://github.com/oemof/oemof/issues/58 and with
```python
print(energysystem.results[storage].add_cap)
```
I get much higher values. Does anyone has a hint which variable I can trust?

Comparing with the results from pahesmf the add_cap variable seems to be true. But what is the maximum soc then?

@ckaldemeyer 
@simonhilpert

**Comment by uvchik** [comment]
In the `solph.variables` module I can find the following equation on line [251ff](../blob/dev/oemof/solph/variables.py#L251). So the cap-variable should not be greater than the total capacity.
```
cap(t) <= add_cap + cap_max
```
Is `cap_max=0` ?

**Comment by caro-rli** [comment]
Yes cap_max is 0 (by default and in the storage_invest example even set to 0)

**Comment by caro-rli** [comment]
>I get much higher values.

And also I meant I get much higher values with the add_cap variable. The maximum cap(t) is much lower (if cap(t) is the storage variable in type "other"), but also not below 1, so it could also not be the percental value.

**Comment by uvchik** [comment]
I also do not think it is the percental value. For the storage_invest example I get the following results using the following code:

```python
>>> energysystem.optimize()
>>> es_df = tpd.EnergySystemDataFrame(energy_system=energysystem)
>>> print(es_df.data_frame.loc[idx[:, :, 'other', storage.uid, :], :].groupby(level=0).max())
335711.806345

>>> print(energysystem.results[storage].add_cap)
11041116.6957001
```

If other is really the soc of the storage it seems to be bug.

**Comment by uvchik** [comment]
It seems to me that the values of "other" and "input" are accidentally the same. This might happen in the `to_pandas` module or in the `results` method of the `optimisation_model` module.

```python
>>> print(es_df.data_frame.loc[idx[:, :, :, storage.uid, :], :].groupby(level=2).sum())
input   3.969496e+08
other   3.969496e+08
output  4.961870e+08

 >>> print(es_df.data_frame.loc[idx[:, :, :, storage.uid, :], :].groupby(level=2).max())             
input   335711.806345
other   335711.806345
output  938557.781821
```

@caro-rli : This makes sense and is easy to understand that the maximum of the input is lower than the capacity. So I would trust the `energysystem.results[storage].add_cap` statement.

**Comment by ckaldemeyer** [comment]
The result-object has changed and the outputlib dataframe has not been adapted yet (because we didn't know about the changes):

optimization_model.py:

        # TODO: Maybe make the results dictionary a proper object?
        result = UD()
        result.objective = self.objective
        for entity in self.entities:
            if ( isinstance(entity, cp.Transformer) or
                 isinstance(entity, cp.Transport)   or
                 isinstance(entity, cp.Source)):
                if entity.outputs:
                    result[entity] = result.get(entity, UD())
                for o in entity.outputs:
                    result[entity][o] = [self.w[entity.uid, o.uid, t].value
                                         for t in self.timesteps]

                for i in entity.inputs:
                    result[i] = result.get(i, {})
                    result[i][entity] = [self.w[i.uid, entity.uid, t].value
                                         for t in self.timesteps]

            if isinstance(entity, cp.sources.DispatchSource):
                result[entity] = result.get(entity, UD())
                # TODO: Why does this use `entity.outputs[0]`?
                result[entity][entity] = [self.w[entity.uid,
                                                 entity.outputs[0].uid,
                                                 t].bounds[1]
                                          for t in self.timesteps]

            if isinstance(entity, cp.Sink):
                for i in entity.inputs:
                    result[i] = result.get(i, {})
                    result[i][entity] = [self.w[i.uid, entity.uid, t].value
                                         for t in self.timesteps]

            if isinstance(entity, cp.transformers.Storage):
                result[entity] = result.get(entity, UD())
                result[entity][entity] = [getattr(self, str(Storage)
                                                  ).cap[entity.uid, t].value
                                          for t in self.timesteps]

            block = getattr(self, str(type(entity)))

            # these are the variables which are not yet in the df..
            for attribute in ["add_cap", "add_out"]:
                values = getattr(block, attribute, None)
                if values:
                    result[entity] = result.get(entity, UD())
                    setattr(result[entity], attribute, values[entity.uid]())

        if hasattr(self, "dual"):
            for bus in getattr(self, str(Bus)).objs:
                if bus.balanced:
                    result[bus] = result.get(bus, {})
                    result[bus][bus] = [
                        self.dual[getattr(self, str(Bus)).balance[
                            (bus.uid, t)]]
                        for t in self.timesteps]

The proper creation with the add_caps will be integrated in the "new" outputlib version which Martin and me are tuning on "features/fix-outputlib-dev". I am really busy busy with my paper and this investment model testing doesn't fix well at the moment :-) But maybe we can hotfix this.. I'll talk to s3pp if we can already merge back and adapt it for the new variables.

**Comment by uvchik** [comment]
@ckaldemeyer, @s3pp : Would be nice to have it fixed, soon. But if the error comes from the DataFrame creation you can plot the soc using the results dictionary.

```python
plt.plot(energysystem.results[storage][storage])
plt.show()
```

Now the `add_cap` variable and the maximum of the soc should be the same. Test the following:
```python
print(energysystem.results[storage].add_cap)
print(max(energysystem.results[storage][storage]))
```

**Comment by ckaldemeyer** [comment]
I have created a new branch and added the "new" dataframe creation which should fix the problem with the SOC: https://github.com/oemof/oemof/tree/features/outputlib-fix-df-creation

A rough check looked well but please *test* your own examples before we merge back. Caros investment variables are still NOT included and can be accessed like Uwe has described above.

The reason why I haven't integrated investment variables is that they have another dimension (scalar) than all other data (time series of length N) and need to be treated differently. One option would be to set them as an attribute but I don't think this is the best method.

Günni and me agreed it makes sense to combine the result-object and the dataframe and only have one result object instead of redundant structures (that lead to errors as we have experienced). But this takes some time which -at least I- don't have until mid of February. But until then, the fix above might be enough..

Please check if it works!

**Comment by simonhilpert** [comment]
Generally I think the result object and the pandas Dataframe do not have a consistent structure right now for all results...  

I think we need a "name" for results that are not related to an edge but only to the component/bus.

E.G. SOC of storages, Investment variables like add_out, add_cap (although these could be linked to an edge as well because theses vars will extend to upper bound of an edge variable)

**Comment by ckaldemeyer** [comment]
> Generally I think the result object and the pandas Dataframe do not have a consistent structure right now for all results...

I agree.

> I think we need a "name" for results that are not related to an edge but only to the component/bus.
> E.G. SOC of storages, Investment variables like add_out, add_cap (although these could be linked to an edge as well because theses vars will extend to upper bound of an edge variable)

I think we first need a structure which then includes a suitable naming. Do you think we should keep the general idea of the dataframe and extend it or do you have ideas for another structure?

Here's the current structure from example_app.py with 2 timesteps:

                                                       val
	bus_uid bus_type type   obj_uid datetime                      
	b_el    el       input  pp_chp  2012-01-01 00:00:00   9.796349
		                            2012-01-01 01:00:00  10.002964
		                    pp_coal 2012-01-01 00:00:00   7.795251
		                            2012-01-01 01:00:00   7.389736
		                    pp_gas  2012-01-01 00:00:00   0.000000
		                            2012-01-01 01:00:00   0.000000
		                    pp_lig  2012-01-01 00:00:00  11.800000
		                            2012-01-01 01:00:00  11.800000
		                    pp_oil  2012-01-01 00:00:00   0.000000
		                            2012-01-01 01:00:00   0.000000
		                    pv      2012-01-01 00:00:00   0.000000
		                            2012-01-01 01:00:00   0.000000
		                    wind_on 2012-01-01 00:00:00  18.431400
		                            2012-01-01 01:00:00  18.630300
		             other  duals   2012-01-01 00:00:00  25.000000
		                            2012-01-01 01:00:00  25.000000
		                    pv      2012-01-01 00:00:00   0.000000
		                            2012-01-01 01:00:00   0.000000
		                    wind_on 2012-01-01 00:00:00  18.431400
		                            2012-01-01 01:00:00  18.630300
	b_th    th       input  pp_chp  2012-01-01 00:00:00   7.347262
		                            2012-01-01 01:00:00   7.502223
		             other  duals   2012-01-01 00:00:00  33.333333
		                            2012-01-01 01:00:00  33.333333
	coal    coal     output pp_coal 2012-01-01 00:00:00  19.987823
		                            2012-01-01 01:00:00  18.948041
	gas     gas      output pp_chp  2012-01-01 00:00:00  24.490872
		                            2012-01-01 01:00:00  25.007410
		                    pp_gas  2012-01-01 00:00:00   0.000000
		                            2012-01-01 01:00:00   0.000000
	lignite lignite  output pp_lig  2012-01-01 00:00:00  28.780488
		                            2012-01-01 01:00:00  28.780488
	oil     oil      output pp_oil  2012-01-01 00:00:00   0.000000
		                            2012-01-01 01:00:00   0.000000

One idea would be to save "add_cap" by adding an entry "add_cap_XY", etc. under "other". This could either be realized by saving the scalar value for one timestamp or by repeating it N times which would be even easier..

**Comment by uvchik** [comment]
@ckaldemeyer, thank you it works for me. @caro-rli, could you test it, too

I do not think it is a good idea to add the scalar values to the DataFrame. In my opinion we should create an dictionary or DataFrame with a similar structure containing the scalars. Furthermore I would like a dictionary holding some meta results such as solver time etc.. We also could add these kind of results to the simulation object.

Shall we open a new issue to discuss the structure of the results because this issue has a different request and should be closed if @caro-rli tests are successful.

**Comment by ckaldemeyer** [comment]
@uvchik: Yes, let's create another issue. I think it makes sense to get a common structure here and have Günni nearby to keep it sorted.

**Comment by ckaldemeyer** [comment]
@caro-rli and @s3pp : can you test the dataframe creation, too? If it's o.k. we can merge back into dev. And I propose we do a hotfix since this the error is also on the "stable" version.

**Comment by s3pp** [comment]
Everything works fine imo. :+1:

**Comment by ckaldemeyer** [comment]
Even of @caro-rli hasn't tested yet, I think it should be o.k. to merge back if it works for 3 users, or not!?

**Comment by uvchik** [comment]
:+1:

**Comment by caro-rli** [comment]
Sorry for the delay. Works for me, too. Closing this now..
