### ISSUE TITLE
What do you think about pull-requests?

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#90]
I think pull requests (PR's) are a good way to publish changes to code written by somebody else. I started PR's to avoid unintended changes in e.g. solph. But I have the experience that nobody comments my PR's. Do you think I should just merge it if it works for me? We do not even have proper tests. But if nobody cares for PR's they are senseless.

@oemof/oemof-main : What do you think? Shall I just merge or shall continue using PR's for sensible code parts? PR #84 is an actual example.

**Comment by caro-rli** [comment]
I think PR are basically a good idea, but the (big) problem I see is the responsibility for checking these and free them for merge. Especially when it's about detail questions or features. We have no admin or someone like this who oversees everything (at least I don't :smile:). My opinion is if tests are working (which have to be established, I know..) everyone can merge his/her changes. It might be also a good idea to announce new features (also directly after merge for the developers group, not only with release).

**Comment by uvchik** [comment]
> We have no admin or someone like this who oversees everything.

But maybe we should elect "admins" for different packages.

**Comment by ckaldemeyer** [comment]
+1

**Comment by gnn** [comment]
Pull requests are a great way to strengthen collaboration and ensure that we are a team working on a collective project instead of a group of isolated developers pushing isolated changes into a common repository. @caro-rli is right about the problems concerning responsibilities so we have to establish a process with which we'll handle pull requests. Here's a rough sketch of how I think it could be done:

  0. the person who opened the pull requests assigns the request to somebody who he deems most appropriate; now, there are a few things that can happen:
  1. the assignee doesn't think he's qualified to review the pull request; in that case he can hand assignment back to the original author with a short comment.
  2. the assignee reviews the PR and gives a :+1:, in which case assignment is handed back to the original author which can proceed to merge the PR.
  3. the assignee reviews the PR and deems it not yet in shape for a merge; in that case he can hand back assignment with a comment on how to improve things so that they can be merged.
  4. the assignee rejects the PR (hopefully with an explanation); this can also happen as a result of a discussion in 4.
  5. the assignee, being not particularly skilled at communicating like e.g. me, doesn't respond for "ages"; I think for this case we should agree on both, a time limit (maybe two, a short one for urgent and a slightly longer one for normal PRs) in which there should be at least some reaction to PRs and a default action in case the time limit is violated.

"package admins" are a good idea and can serve as a fallback/default if the opener of a pull request doesn't know a better assignee in step 1. or if 2. kicks in.

And btw.: thanks for bringing PRs up and being persistent in using them @uvchik .

**Comment by uvchik** [comment]
Thank you @gnn this is a very good basis for a discussion.

**Comment by cswh** [comment]
I like it as well. Could we transfer our PR rules into the wiki?

**Comment by uvchik** [comment]
As we created new groups, the members of the groups are the reviewer. If you do not feel qualified to be a reviewer you shouldn't be a member of the group (oemof-solph, oemof-core...) but you can still be a member of oemof and you still can make PRs to add features, fix bugs....
Some groups cover a big repository and not every reviewer is able to check every piece of code but a reviewer should feel quite confident with the package code.

**Comment by uvchik** [comment]
Except of small bug fixes and correction of typos a PR has to be created. External collaborators does not have a choice anyway.
