### ISSUE TITLE
[meeting] 2021 oemof Winter Meeting

### ISSUE THREAD

**Issue by busiing** [oemof/oemof#96]
This issue organises the next oemof meeting.

**Date:  01.12 - 03.12.2021**
**Location: Bremen**

Agenda and further Information: [https://github.com/oemof/oemof/wiki/Meeting-December-2021 (hybrid)](https://github.com/oemof/oemof/wiki/Meeting-December-2021-(hybrid))

Registration closed.

**Comment by joroeder** [comment]
Dear oemof community

We from the Uni Bremen (@uvchik and me) are currently planning the next oemof dev meeting (from 1st to 3rd of December in Bremen) under the motto **"Join-the-devs"**. Our idea is to have an in person meeting for all devs and devs in future with a strong focus on hands-on sessions.

Probably many of us have a lack of time in their daily business when it comes to the development and maintenance of the oemof packages. So why don’t we do this on the next dev meeting?!

So, our suggestion is a combination of plenum sessions for discussion and decision making for undecided issues and the direct implementation in small groups. Also, new people are very welcome and should get involved into the development by assisted tasks like the improvement of docstrings or documentation, or development of new components. Sessions should address solving a specific issue. The character of the meeting should really be on the development.

Also, one major organisational session should be the foundation of the oemof foundation.

We would like to already announce the idea of the next dev meeting in a newsletter next week so that people can already register/show interest. So, please give us a feedback until end of this week if you think such kind of dev meeting is not a good idea. Thank you!

**Comment by jokochems** [comment]
I like the idea and am looking forward to the meeting.

**Comment by jokochems** [comment]
Hey there,

it just crossed my mind that we should distribute some small getting started as a dev info to the participants for all the different packages (basically just copying / pasting the info from the respective docs) and distribute it to the registered participants instructing them to do the setup before. I remember that setting up my fork, environments and stuff took quite some time not usable for productive development in an earlier hands-on session.

Nonetheless, we should plan some time for missing setups / to assist with the setup where there are problems on the first day (about half an hour, I guess for forking, cloning, installing, setting upstreams and stuff).

**Comment by jokochems** [comment]
> 
> 
> Something like this from [oemof/tespy#87 (comment)](https://github.com/oemof/tespy/issues/87#issue-509573675)?
> 
> > **workflow**
> > ```
> > 1. If you did not fork oemof/tespy before:
> >    
> >    * fork tespy to your repositories
> > 
> > 2. clone your repository
> >    
> >    * https: `git clone https://github.com/YOURUSERNAME/tespy.git` or use
> >    * ssh: `git@github.com:YOURUSERNAME/tespy.git`
> > 
> > 3. if the branch oemof_doc_review is in your fork:
> >    
> >    * check out your oemof_doc_review branch (`git checkout -b oemof_doc_review origin/oemof_doc_review`)
> > 
> > 4. Else:
> >    
> >    * create new local branch and pull from upstream (to add before).
> >    * `git remote add upstream https://github.com/oemof/tespy.git`
> >    * `git checkout -b oemof_doc_review`
> >    * `git pull upstream/oemof_doc_review`
> > 
> > 5. push your adjustments to your remote branch (`git push` or `git push --set-upstream origin oemof_doc_review`)
> > 
> > 6. create a PR on oemof/tespy to merge your remote branch in oemof/tespy oemof_doc_review
> > 
> > 7. profit :)! (see https://github.com/oemof/oemof/pull/661)
> > ```

Yeah, exactly like this. :-)

**Comment by markushal** [comment]
Hi everybody, will it be possible to participate remotely (at least for some of the activities?). For me at least this would be great. You could reach a larger audience, and it may also make sense if Corona regulations become more restrictive until December.

**Comment by uvchik** [comment]
I added the registration link above (and here).  In case of limitations e.g. due to new Corona regularities the order of the registration will be relevant. So do not hesitate to register :smile: You have to be vaccinated or recovered to join the meeting.
[https://oemof.org/registration-to-the-15th-oemof-developer-meeting-in-bremen-1-3-december-2021/](https://oemof.org/registration-to-the-15th-oemof-developer-meeting-in-bremen-1-3-december-2021/)

**Comment by joroeder** [comment]
A short update for the dev meeting (see also Wiki [https://github.com/oemof/oemof/wiki/Meeting-December-2021](https://github.com/oemof/oemof/wiki/Meeting-December-2021)

Location:
BIAS – Bremer Institut für angewandte Strahltechnik GmbH, Klagenfurter Straße 5, 28359 Bremen

Option for Hotel, located at the Uni campus:
[https://www.7things.de/hotel-bremen/](https://www.7things.de/hotel-bremen/)

The timetable framework is set up (see Wiki). The Thursday slots will be filled based on the Session "Discussion / Decision making / Prioritising issues" on Wednesday. The basis are the current issues of the packages. If you have a specific topic, please open an issue in the package.

If you have any other general issue/topic besides the handy-on sessions, we need to discuss at the meeting, and that should be considered in the timetable, please post here.

We are looking forward to the meeting! :-)

**Comment by e-zolotarevskaya** [comment]
Hello everyone,
I would like to propose a topic for one of the coding sessions. I'm interested in integrating stochastic programming in oemof. 

You can find a more detailed formulation of the problem in this issue: https://github.com/oemof/oemof-solph/issues/778#

**Comment by jokochems** [comment]
Hi everyone,

I finally managed to revisit https://github.com/oemof/oemof-solph/pull/750 and created a new issue https://github.com/oemof/oemof-solph/issues/793 on multiperiod investment modeling (yet to linked to each other).
I'd like to briefly discuss this and the current plan and status quo in the meeting next week. I think it might be a bit too large for a hands-on session, though.

Looking forward to seeing you in Bremen next week. :-)

**Comment by jokochems** [comment]
Also, I added https://github.com/oemof/oemof-solph/issues/794 on results processing which we might discuss.

**Comment by Fernando3161** [comment]
Hi!
What are the topics of the Parallel Hands-on Sessions?

Could they be broadcasted online? 

FP

**Comment by p-snft** [comment]
I want to discuss the following:

* https://github.com/oemof/oemof-solph/issues/795
* https://github.com/oemof/oemof-solph/pull/753
* https://github.com/oemof/oemof-solph/pull/757
* https://github.com/oemof/oemof-solph/pull/733

**Comment by p-snft** [comment]
> Hi! What are the topics of the Parallel Hands-on Sessions?
> 
> Could they be broadcasted online?

I'd suggest to share screens for some joint hacking.

**Comment by jnnr** [comment]
I would like to move forward with this:
* oemof.tabular
  * https://github.com/oemof/oemof-tabular/pull/21
  * https://github.com/oemof/oemof-tabular/pull/28

I will not be there physically, but can participate remotely when we work on these topics.

**Comment by fwitte** [comment]
I would be interested in https://github.com/oemof/oemof-solph/issues/795 as well, if it is an online viable topic.

**Comment by joroeder** [comment]
We just sent an email with the final details and information to all registered people.

**Comment by fwitte** [comment]
We might also consider updating the webiste and include https://github.com/oemof/oemof/issues/41 on our list.

**Comment by jokochems** [comment]
Here is the etherpad for notes and minutes: https://yopad.eu/p/oemof_dev_2021-365days
The outcome for the individual issues will be documented directly within the respective issue.

**Comment by busiing** [comment]
> We might also consider updating the webiste and include
> 
> * [[website] Improve oemof website #41](https://github.com/oemof/oemof/issues/41)
> 
> on our list.

I would be interested in this as well and am willing to help.
