### ISSUE TITLE
User Meeting 18-20.05.2022 @Europa Universität Flensburg

### ISSUE THREAD

**Issue by joroeder** [oemof/oemof#99]
Date 18.05.-20.05.2022

Location: Flensburg

Organisation: @simnh , (Registration managment: @uvchik , Agenda-support @p-snft , social-events @busiing )

**Comment by jokochems** [comment]
It is still quite a while to go, but I think, I'd like to give an overview over the POMMES cosmos then.
The [dispatch model](https://github.com/pommes-public/pommesdispatch) and the data routine are (about to be) open source, the investment model should be finished by then.

**Comment by busiing** [comment]
Please consider following the [hosting guidelines](https://github.com/oemof/oemof/wiki/How-to-organize-an-oemof-meeting).

**Comment by simnh** [comment]
thanks for the hint ;-)

**Comment by simnh** [comment]
@oemof-developer for the list of topics: https://github.com/oemof/oemof/wiki/Meeting-May-2022

Please add your ideas there...(as most of you are also users ;)

**Comment by simnh** [comment]
I discussed with @uvchik  today and we would propose the following general structure for the meeting: 

* Starting Wednesday after Lunch (13:00)
* Wed-Thursday afternoon strong user focus, 
* Thursday late afternoon (16+) open space for users
* Friday (and late Thu afternoon): Dev focus open for interested users who might want become developer. 

We realise that it might be good to have some space for dev-stuff as well...that's why we came up with this structure. :-) 

Let us know what you think! also: please write down your ideas / whishes / etc. for session in the Wiki.-Page (Would you like to do a hands-on-session? etc..)

**Comment by joroeder** [comment]
> 
>     2. Someone who likes to give a short presentation/update on the association? (I do not know, probably this is just a couple of minutes...but who knows)
> 

We plan to do an open board meeting at the user meeting. So, everybody who is interested can join. This session will also include a short update of the current status. I will appoint @p-snft @c-moeller and me to this session.

**Comment by uvchik** [comment]
If you know users from the wider circle, please contact them personally and ask them for presentation.

We want to provide a detailed program on April, 22nd. So, please add your topics and presentations until April, 20th.

**Comment by jokochems** [comment]
Hi there, sorry to jump in only now: Unfortunately, I can't make it to Flensburg before around 16.00 on Wednesday. Would it be possible to swap the sessions (or my slot only)? Thank you! :-)

**Comment by p-snft** [comment]
We had the meeting. Closed.
